(()=>{
'use strict';
const W=window.WB;if(!W)return;
const VERSION='card-db-clean-1.5';
const QB_PROFILES=[{"scale":723.0155570565015,"data":"JTMvJik3JSIcER8XAxIR8M/U2NgONi49KiwjFiMl9/Lq2OHgt8vmNSojHSEyNCIm6t/f8/blxdjdJR4b9N0XOPwY49/uDfbw1PED59oHLT48QvDy4uADBvz/zNjPAwEIJDcxDeXc397pCAEFz8vhNh0D/hsA5+wE5gH9AwsMt8vq/vi9xNzE7Rnh0vUfICXvBAYD/fv8+/v7/ezMr6OI1x8lExkYEAsJBQMAAPPn08XoKT87ERokDwUD/vry6OPe2/c6QUBFCQsUBf358vDq3+DS2wg1OztCBPkD/v7y4d7d3ufrBjoxJjM/Avb++fft29DJ2uz1G047FjE6A/386err5d3a4enlAxgqMTgqAwD15evx8eng3d7u+PIgMSgeDA0QEhUYGh0dHRn6x7+86v0G8O3s6+7x9Pf6Aw0UISL/17/CBAL8/P4AAwUHDxkaSDTQxbu2DBINDA8QEhITFhgbOA3Nv7izEx4VEhcZGhodFxIWCubev7C1EiASDBEWGyAiGxUV/NvSyKuuEBYPEBETFxsfHBgX/u/bz6u7EhIZHBMTGRsgHxsVICnw2Mfq"},{"scale":662.5510622247602,"data":"IyAqLCEgODgkLRklDQIPC+3gK+3Y9B8tMjAiJxoaKPjv597qAr3M3QkuIRsTKjEhKuvo4/j2AcXk2PgiEQ7qBioOGvLn9Qz24NPuA/bo9yYtPy8W9uXt8w4A3ubb0t0R/RQoMSH44u7v6QQCxsrW4gYmB/wOBef3++r+/gMQw8nF5PP80MDWzc0Q/NkAFR0gBQf/AwQDBAH58/nwy7CbiNodCxUaIh8OCwj/9/z23tPS/zZFCRAfLSoJAf7+9e3m3dYORUA+Aw8GDw/++/Xz7ubj4+cfMDU6CQz6/gj/9+fe29Ho8xQrNB0pCw79/gP38+PTysnm+iQ/NQMzAggCAfHj6+jf3uX19wwiIiM7BQcF/e7o9fjw7u/f6O74JCst+wQMDg8QCgsUGxIN9dC8tOnx6fDy6uXm7fX7/QAFFSkj68y99/z98fL6/wAABAoMHEQOv7+3/AwaBAQODQ8TEBIUGzDyy8G0AQwlFwsVFBgdFxwSDPzb2M20AAEcFAcMExkhKSkWCO3LzM+sAgETEBEiHRkaHh0VDgPm48qwAwULFSgtIhsbHBsdFCsj3svM"},{"scale":522.7974147148424,"data":"7+vr/Pjy8/Ds7eYM/xgXFfD18fvdA/jx9vX5LzUSByAG7Ov69gPl3s7d/AUYOCoiFyT33+vpBQbcy9XTCwkhMxgKEgfx3ODbBQrc0RXqBxMoLh4YA+IE9vP5FRPn8BwEHB8R/AMxFeIK+fnl/PrU5fL4C/vbADMxEvT++Pjh6+ryAxgbHg0ZESwwIBz67PrqBQT6AwP8/AIDAgHZmpCItf78GBYEDxENIR8e/f8G7+fo9g4IIBz+9/oEFx0R/AUKEwv2/AD9Ihv/8vf6DBoI/g4eHB8I+fzyHxgA7+3zCRMG+PAKGS4dDPHuGRH/7uv1DhMO8u4BDC8UAPgIAPn17O34Bv717/H/BRcH9vUT+P399+Hk7/Dz+PgACxzw4vMB/AEH/voE/Pv39/n46eLhBR4T3eAG9u4I39Xc8vbrECkpFf392NwXIyIZ4Nbn+vfoGEEUAv0F1tsTIR4a6M7o+PbhEBT+AAUOztcKHyId6tbq+//u8unr+A8Z1t4IIyIS49vlBhL+8tvyAQb0AxQeHCEa7gEVFAX2+fb3BRD9FRYKESwtERIUC/T1AiARICUU"},{"scale":514.430855079784,"data":"8Ovq/fjy9fDu7ucKABcWFPHz8PrdA/rx9fb4LjMTBx4H7ev59gLm387e+gUYOCkhEyP44OzqBAbdzNTVCAwiMxcJEgvw3eHdBgrc0hHsBxEnLB0bA+EF9PL5FRPm7h0EGR0S/gIwF+QK+Prm+/jX5vP3Cvza/TIxE/X9+Pbg7O3wAhkaHQ8XFSsxHx756/nrBAX8AQP7/AADBwXUlI6Ipu77GBIPEhkOGiAcBgQF5djY9BEEIRsB9vj9Fx8UAQcJCxb//f7+IRsA8/P6ExoOBhIYDAoH9/r3HxsD8e31DhYKAPkLGigXC/L3IRgA7u33CxAF9+n7EjIWEPkDDAT06+35BgL59fX9BBIM//UM/f0A+OHg6/D1+fr/CBX96fcBBQcGAg4OCQsLAvwD5uPeAyQh3dz67eX/4tfc8PbwEyIYFwQC19QRHhsZ6dTg7e/pDksbAwD90tMMHiEh7dTm8PHl+Bf+AwMK0NMFICcf7tbn9v3t6+Tx9Qwa09oGICcV697g/hD+9uDu8wf4+AcUGSIX+vgKExD/+fn0AAr1FRQKCSorFg8RDgD/CjwkHiMU"}]
const CARDS=Object.freeze({
 quickBlader:Object.freeze({id:'quickBlader',officialId:10021110,name:'刹那のクイックブレイダー',label:'刹那のクイックブレイダー',class:'ロイヤル',type:'フォロワー',set:'ベーシック',cost:1,atk:1,life:1,maxCount:3,tags:['疾走'],category:'疾走',route:{type:'storm',cost:1,baseDamage:1,evolveBonus:2,superBonus:3},recognition:{enabled:true,method:'hand-title-cost-gate-v5',threshold:.94,candidateThreshold:.90,stableFrames:3,rescueFrames:2,rescueThreshold:.965,costRequired:true,featureLength:432,profiles:QB_PROFILES}}),
 zetaBeatrix:Object.freeze({id:'zetaBeatrix',officialId:10424110,name:'真紅と群青・ゼタ＆ベアトリクス',label:'ゼタ＆ベアトリクス',class:'ロイヤル',type:'フォロワー',cost:4,atk:3,life:2,maxCount:3,tags:['突進','エンハンス6','疾走'],category:'疾走・フィニッシャー',recognition:{enabled:false}}),
 barbaros:Object.freeze({id:'barbaros',officialId:null,name:'逆行の咎人・バルバロス',label:'バルバロス',class:'ロイヤル',type:'フォロワー',cost:7,atk:4,life:3,maxCount:3,tags:['疾走','海賊旗'],category:'フィニッシャー',recognition:{enabled:false}})
});
const META=Object.freeze({version:VERSION,complete:false,scope:'verified-tactical-subset',registeredCards:Object.keys(CARDS).length,verifiedCards:Object.keys(CARDS).length,recognitionEnabledCards:Object.values(CARDS).filter(c=>c.recognition?.enabled).length,updatedAt:'2026-09-18',note:'全カードDBではありません。検証済みカードから段階拡張します。',recognitionSafety:'image + OCR cost gate / latest stable hand backscan / 3-frame consensus / boundary-limited 2-frame high-confidence rescue / absence remains unknown'});
const clone=x=>JSON.parse(JSON.stringify(x));
function decodeProfile(p){const raw=atob(p.data),v=new Float32Array(raw.length);let norm=0;for(let i=0;i<raw.length;i++){let q=raw.charCodeAt(i);if(q>127)q-=256;const x=q/Number(p.scale||1);v[i]=x;norm+=x*x}norm=Math.sqrt(norm)||1;for(let i=0;i<v.length;i++)v[i]/=norm;return v}
const decoded=new Map();
function recognitionProfiles(id){const card=CARDS[id];if(!card?.recognition?.enabled)return[];if(!decoded.has(id))decoded.set(id,card.recognition.profiles.map(decodeProfile));return decoded.get(id)}
function tacticalCards(){return Object.values(CARDS).map(c=>{const x=clone(c);if(x.recognition)delete x.recognition.profiles;return x})}
function get(id){return CARDS[id]?clone(CARDS[id]):null}
function recognitionCards(){return Object.values(CARDS).filter(c=>c.recognition?.enabled).map(c=>({id:c.id,label:c.label,expectedCost:c.cost,threshold:c.recognition.threshold,candidateThreshold:c.recognition.candidateThreshold??c.recognition.threshold,stableFrames:c.recognition.stableFrames,rescueFrames:c.recognition.rescueFrames??2,rescueThreshold:c.recognition.rescueThreshold??c.recognition.threshold,costRequired:c.recognition.costRequired!==false,featureLength:c.recognition.featureLength,method:c.recognition.method}))}
W.CardDB={version:VERSION,meta:META,get,tacticalCards,recognitionCards,recognitionProfiles};
W.registerModule('card-db',VERSION);
W.log('module-ready',{module:'card-db',version:VERSION,complete:false,verifiedCards:META.verifiedCards,recognitionEnabledCards:META.recognitionEnabledCards});
})();