(()=>{
'use strict';
const WB=window.WB;if(!WB)return;
const VERSION='diagnostics-clean-1.8';WB.registerModule('diagnostics',VERSION);
const EXPECTED={video1:{turns:{top1:'~14.5s',bottom1:'~18-19s',top2:'~21-22s',bottom2:'~25s'},class:'ナイトメア',extraPP:'後攻1Tで使用可',epSep1T:'使用不可'},video2:{turns:{bottom1:'~5.8s',top1:'~8.3s',bottom2:'~11.4s',top2:'~14.9s'},prefixGuard:'3.5sの偽top1は後続3区間以上が一致しHUD再確認で不成立の場合のみ除外',playOrder:'先攻',statePoints:[{time:88.406,pp:'8/8',opponentHp:16},{time:91.699,pp:'5/8',opponentHp:16},{time:95.012,pp:'0/8',opponentHp:14}],extraPP:'先攻のため使用不可',epSep8T:'実画像で使用可認識',ward:'先攻の自分1Tはルールでなし確定 / 8Tは盾表示であり確認 / フォロワーあり非盾は安全上未確認',board:'8T旗のみは攻撃可能総打点0を自動確定 / フォロワーごとに攻撃力と外周の緑色攻撃可能リングを対応確認 / 相手守護は別状態で保持',tacticalSummary:'カード固有の固定欄を廃止 / 戦術情報カタログから手札・旗・追加打点を動的管理 / 刹那のクイックブレイダーを1PP疾走候補として集約表示',mulligan:'冒頭録画でも初期4枚を取得',class:'VS画面未収録なら未判定'}};
function loadedScripts(){return [...document.scripts].map(s=>s.src?new URL(s.src,location.href).pathname:'inline').filter(Boolean)}
function runtimeInvariant(){const scripts=loadedScripts(),fixScripts=scripts.filter(s=>/fix-v[^/]*\.js/i.test(s)),local=scripts.filter(s=>/\/(app-core|turn-recognition|mulligan-class|state-recognition|review-engine|diagnostics)\.js$/.test(s));const h=document.querySelector('header h1')?.textContent||'',sub=document.querySelector('header p')?.textContent||'',expected=['app-core','turn-recognition','mulligan-class','state-recognition','review-engine','diagnostics'],loaded=new Set(local.map(s=>(s.match(/\/([^/]+)\.js$/)||[])[1]).filter(Boolean)),modulesOk=expected.every(n=>loaded.has(n))&&loaded.size===expected.length,headerOk=h.includes(`v${WB.APP.version}`),subheaderOk=sub.includes(WB.APP.revision),oldVersionTextVisible=/v3\.4|v4\.9\.4|20s/.test(document.body.innerText);return{ok:fixScripts.length===0&&modulesOk&&headerOk&&subheaderOk&&!oldVersionTextVisible,header:h,subheader:sub,fixScripts,cleanModules:local,modulesOk,headerOk,subheaderOk,serviceWorkerController:navigator.serviceWorker?.controller?.scriptURL||null,oldVersionTextVisible,checkedAt:new Date().toISOString()}}
function diagnostic(){const v=WB.video,inv=runtimeInvariant();return{format:'shadowverse-wb-diagnostic-v4.12.0-clean',build:WB.APP.build,version:WB.APP.version,revision:WB.APP.revision,createdAt:new Date().toISOString(),userAgent:navigator.userAgent,standalone:matchMedia('(display-mode: standalone)').matches,serviceWorker:{reported:WB.swInfo,controller:navigator.serviceWorker?.controller?.scriptURL||null},modules:clone(WB.modules),runtimeInvariant:inv,video:WB.videoMeta?{...WB.videoMeta,duration:Number.isFinite(v?.duration)?+v.duration.toFixed(3):null,currentTime:Number.isFinite(v?.currentTime)?+v.currentTime.toFixed(3):null,width:v?.videoWidth||null,height:v?.videoHeight||null}:null,targetSide:WB.targetSide(),playOrder:WB.playOrder(),turnTimeline:clone(WB.turnTimeline),turnValidation:clone(WB.turnValidation),seek:{count:WB.seekCount,reasons:clone(WB.seekReasons)},mulliganPreview:clone(WB.mulligan),classDetection:clone(WB.classDetection),stateCapture:clone(WB.stateCapture),tacticalStateV1:clone(window.__wbTacticalV1||null),lethalStateV2:clone(window.__wbLethalV2||null),counterfactualTreeV1:clone(window.__wbCounterfactualV1||null),scenes:WB.scenes.map(s=>({id:s.id,turn:s.turn,time:s.time,playOrder:s.playOrder,matchup:s.matchup,deck:s.deck,note:s.note})),errors:clone(WB.errors),regressionBaselines:EXPECTED,events:clone(WB.events)}}
function clone(x){try{return structuredClone(x)}catch{return x==null?x:JSON.parse(JSON.stringify(x))}}
function reviewExport(){return{format:'shadowverse-wb-review-v4.12.0-clean',build:WB.APP.build,source:WB.videoName,createdAt:new Date().toISOString(),video:WB.videoMeta?{...WB.videoMeta}:null,turnRecognition:{method:'stable13-primary+validated-prefix-reconciliation+early-hud-light-validation',stableSha:WB.TurnRecognition?.stableSha||null,timeline:clone(WB.turnTimeline),validation:clone(WB.turnValidation)},mulligan:clone(WB.mulligan),classDetection:clone(WB.classDetection),stateCapture:clone(WB.stateCapture),tacticalStateV1:clone(window.__wbTacticalV1||null),scenes:WB.scenes.map((s,i)=>({no:i+1,turn:s.turn,timeSeconds:s.time,playOrder:s.playOrder,matchup:s.matchup,deck:s.deck,note:s.note})),lethalStateV2:clone(window.__wbLethalV2||null),counterfactualTreeV1:clone(window.__wbCounterfactualV1||null)}}
WB.Diagnostics={version:VERSION,diagnostic,runtimeInvariant,expected:EXPECTED};
WB.onReady(()=>{const inv=runtimeInvariant();WB.log('clean-runtime-invariant',inv);WB.$('#exportDiag')?.addEventListener('click',async()=>{const d=diagnostic();WB.log('diagnostic-export',{format:d.format,runtimeOk:d.runtimeInvariant.ok});await WB.shareJsonFile(d,`shadowverse-wb-diagnostic-v4.12.0-${new Date().toISOString().replace(/[:.]/g,'').slice(0,15)}.json`)});WB.$('#showDiag')?.addEventListener('click',()=>{WB.$('#diagView').textContent=JSON.stringify(diagnostic(),null,2)});WB.$('#exportReview')?.addEventListener('click',()=>WB.downloadJSON(reviewExport(),'review.json'));WB.$('#diagView').textContent=`Build ${WB.APP.build}\n統合モジュール: ${WB.modules.map(x=>x.name).join(', ')}\n旧fix読込: ${inv.fixScripts.length}本`;WB.log('module-ready',{module:'diagnostics',version:VERSION,format:'shadowverse-wb-diagnostic-v4.12.0-clean'})});
})();
