(()=>{
'use strict';
const WB=window.WB;if(!WB)return;
const VERSION='diagnostics-clean-1.31';WB.registerModule('diagnostics',VERSION);
const EXPECTED={video1:{turns:{top1:'~14.5s',bottom1:'~18-19s',top2:'~21-22s',bottom2:'~25s'},class:'ナイトメア',extraPP:'後攻1Tで使用可',epSep1T:'使用不可'},video2:{turns:{bottom1:'~5.8s',top1:'~8.3s',bottom2:'~11.4s',top2:'~14.9s'},prefixGuard:'3.5sの偽top1は後続3区間以上が一致しHUD再確認で不成立の場合のみ除外',playOrder:'先攻',statePoints:[{time:88.406,pp:'8/8',opponentHp:16},{time:91.699,pp:'5/8',opponentHp:16},{time:95.012,pp:'0/8',opponentHp:14}],extraPP:'先攻のため使用不可',epSep8T:'実画像で使用可認識',ward:'先攻の自分1Tはルールでなし確定 / 8Tは盾表示であり確認 / フォロワーあり非盾は安全上未確認',board:'8T旗のみは攻撃可能総打点0を自動確定 / フォロワーごとに攻撃力と外周の緑色攻撃可能リングを対応確認 / 確定した盤面打点は合計と内訳をまとめて出力 / 相手守護は別状態で保持',tacticalSummary:'カード固有の固定欄を廃止 / 独立カードDBから手札・旗・追加打点を動的管理 / カード画像認識は従来タイトル帯＋露出カードアンカーの二重経路 / 境界スコアは同一安定手札スロットの複数フレームを合議し、強いコスト確定がない場合でも4フレーム同一画像1位・3フレーム候補域・安定した上位3フレーム・同一コスト仮説が揃った場合だけ救済し、強い別コスト証拠は拒否 / 演出で現在手札のコスト円検出が一時欠落した場合は0件区間を安定手札とせず、現在時刻で見えている2個以上のコスト円位置が短時間後の安定窓に連続する場合だけ前方収束窓を現在手札として採用 / アンカーはコスト円基準で角度±10度・中心±4pxを探索し手札枚数や扇状配置変化へ追従 / 従来タイトル閾値は維持 / カードDBは各カードの許容表示コストだけを保持 / 表示コストはカードIDに依存しないOCR＋数字テンプレートで判定 / 実機検証済み1コストテンプレート5種＋7コストテンプレート5種をカード非依存で共用し、各閾値0.98を維持したまま表示コスト中心を±2px探索 / ゼタは4・エンハンス6の両表示を許可 / 同じ表示コスト7の認識結果は今後の7コストカードにも共用 / 現在手札は自分・相手どちらのターンでも画面下から判定し、相手ターンでは履歴追跡を行わず現在手札だけを扱う / 自分ターンで未確定カードがあれば同じ自分ターン内を最大約1.35秒遡って1つ前の安定手札も追跡 / 直前手札で確認したカードは現在手札との差分だけ履歴として別記録し現在手札・リーサル計算には戻さない / 未検出は0枚と断定しない / 相手ターン開始直後80ms以内だけ、現在4フレームが同一画像1位・0.89以上・スコア幅0.002以内・同一表示コスト仮説4/4を満たし、直前約0.52秒内の同一手札配置を20ms刻みで二位相サンプリングして既存通常条件で同カードを1枚認識した場合に限り現在手札として継続救済 / 自分ターンのドロー直後など、同一カード候補の画像一致度が明確に上昇している場合だけ最大約0.24秒先の同一手札配置を再確認し、既存通常条件を通過したカードだけ現在手札へ採用 / 通常画像閾値0.90と表示コストテンプレート閾値0.98は維持 / 現在状態は判断入力スナップショットへ統合し、現在手札・PP・HP・守護・確定打点・未確認項目・候補ルートを同一オブジェクトで診断出力 / historyObservedは現在手札へ昇格しない',mulligan:'冒頭録画でも初期4枚を取得',class:'VS画面未収録なら未判定'}};
function loadedScripts(){return [...document.scripts].map(s=>s.src?new URL(s.src,location.href).pathname:'inline').filter(Boolean)}
function runtimeInvariant(){const scripts=loadedScripts(),fixScripts=scripts.filter(s=>/fix-v[^/]*\.js/i.test(s)),local=scripts.filter(s=>/\/(app-core|turn-recognition|mulligan-class|card-db|hand-recognition|state-recognition|review-engine|diagnostics)\.js$/.test(s));const h=document.querySelector('header h1')?.textContent||'',sub=document.querySelector('header p')?.textContent||'',expected=['app-core','turn-recognition','mulligan-class','card-db','hand-recognition','state-recognition','review-engine','diagnostics'],loaded=new Set(local.map(s=>(s.match(/\/([^/]+)\.js$/)||[])[1]).filter(Boolean)),modulesOk=expected.every(n=>loaded.has(n))&&loaded.size===expected.length,headerOk=h.includes(`v${WB.APP.version}`),subheaderOk=sub.includes(WB.APP.revision),oldVersionTextVisible=/v3\.4|v4\.9\.4|20s/.test(document.body.innerText);return{ok:fixScripts.length===0&&modulesOk&&headerOk&&subheaderOk&&!oldVersionTextVisible,header:h,subheader:sub,fixScripts,cleanModules:local,modulesOk,headerOk,subheaderOk,serviceWorkerController:navigator.serviceWorker?.controller?.scriptURL||null,oldVersionTextVisible,checkedAt:new Date().toISOString()}}
function diagnostic(){const v=WB.video,inv=runtimeInvariant();return{format:'shadowverse-wb-diagnostic-v4.13.22-clean',build:WB.APP.build,version:WB.APP.version,revision:WB.APP.revision,createdAt:new Date().toISOString(),userAgent:navigator.userAgent,standalone:matchMedia('(display-mode: standalone)').matches,serviceWorker:{reported:WB.swInfo,controller:navigator.serviceWorker?.controller?.scriptURL||null},modules:clone(WB.modules),runtimeInvariant:inv,video:WB.videoMeta?{...WB.videoMeta,duration:Number.isFinite(v?.duration)?+v.duration.toFixed(3):null,currentTime:Number.isFinite(v?.currentTime)?+v.currentTime.toFixed(3):null,width:v?.videoWidth||null,height:v?.videoHeight||null}:null,targetSide:WB.targetSide(),playOrder:WB.playOrder(),turnTimeline:clone(WB.turnTimeline),turnValidation:clone(WB.turnValidation),seek:{count:WB.seekCount,reasons:clone(WB.seekReasons)},mulliganPreview:clone(WB.mulligan),classDetection:clone(WB.classDetection),stateCapture:clone(WB.stateCapture),cardDB:clone(WB.CardDB?.meta||null),displayedCostRecognition:clone(WB.DisplayedCostRecognition?.meta||null),handRecognition:clone(WB.tacticalHandRecognition||null),tacticalStateV1:clone(window.__wbTacticalV1||null),decisionInputV1:clone(window.__wbDecisionInputV1||null),lethalStateV2:clone(window.__wbLethalV2||null),counterfactualTreeV1:clone(window.__wbCounterfactualV1||null),scenes:WB.scenes.map(s=>({id:s.id,turn:s.turn,time:s.time,playOrder:s.playOrder,matchup:s.matchup,deck:s.deck,note:s.note})),errors:clone(WB.errors),regressionBaselines:EXPECTED,events:clone(WB.events)}}
function clone(x){try{return structuredClone(x)}catch{return x==null?x:JSON.parse(JSON.stringify(x))}}
function reviewExport(){return{format:'shadowverse-wb-review-v4.13.22-clean',build:WB.APP.build,source:WB.videoName,createdAt:new Date().toISOString(),video:WB.videoMeta?{...WB.videoMeta}:null,turnRecognition:{method:'stable13-primary+validated-prefix-reconciliation+early-hud-light-validation',stableSha:WB.TurnRecognition?.stableSha||null,timeline:clone(WB.turnTimeline),validation:clone(WB.turnValidation)},mulligan:clone(WB.mulligan),classDetection:clone(WB.classDetection),stateCapture:clone(WB.stateCapture),cardDB:clone(WB.CardDB?.meta||null),displayedCostRecognition:clone(WB.DisplayedCostRecognition?.meta||null),handRecognition:clone(WB.tacticalHandRecognition||null),tacticalStateV1:clone(window.__wbTacticalV1||null),decisionInputV1:clone(window.__wbDecisionInputV1||null),scenes:WB.scenes.map((s,i)=>({no:i+1,turn:s.turn,timeSeconds:s.time,playOrder:s.playOrder,matchup:s.matchup,deck:s.deck,note:s.note})),lethalStateV2:clone(window.__wbLethalV2||null),counterfactualTreeV1:clone(window.__wbCounterfactualV1||null)}}
WB.Diagnostics={version:VERSION,diagnostic,runtimeInvariant,expected:EXPECTED};
WB.onReady(()=>{const inv=runtimeInvariant();WB.log('clean-runtime-invariant',inv);WB.$('#exportDiag')?.addEventListener('click',async()=>{const d=diagnostic();WB.log('diagnostic-export',{format:d.format,runtimeOk:d.runtimeInvariant.ok});await WB.shareJsonFile(d,`shadowverse-wb-diagnostic-v${WB.APP.version}-${new Date().toISOString().replace(/[:.]/g,'').slice(0,15)}.json`)});WB.$('#showDiag')?.addEventListener('click',()=>{WB.$('#diagView').textContent=JSON.stringify(diagnostic(),null,2)});WB.$('#exportReview')?.addEventListener('click',()=>WB.downloadJSON(reviewExport(),'review.json'));WB.$('#diagView').textContent=`Build ${WB.APP.build}\n統合モジュール: ${WB.modules.map(x=>x.name).join(', ')}\n旧fix読込: ${inv.fixScripts.length}本`;WB.log('module-ready',{module:'diagnostics',version:VERSION,format:'shadowverse-wb-diagnostic-v4.13.22-clean'})});
})();
