(()=>{
  const PATCH='4.9.3-20260915-13b',$q=s=>document.querySelector(s);
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  document.documentElement.dataset.wbLatestUi='493';
  function relabel(){const p=$q('#counterfactualPanel490');if(!p)return false;const labels=[['#cfPp490','手番側PP'],['#cfBar490','自分手札：バルバロス'],['#cfZeta490','自分手札：ゼタ＆ベアトリクス']];for(const [sel,text] of labels){const e=$q(sel),lab=e?.closest('label');if(lab){for(const n of [...lab.childNodes]){if(n.nodeType===Node.TEXT_NODE){n.textContent=text;break}}}}const map=[['#cfExtra490','手番側ExPP使用可'],['#cfEp490','手番側EP使用可'],['#cfSep490','手番側SEP使用可']];for(const [sel,text] of map){const e=$q(sel),lab=e?.closest('label');if(lab){const nodes=[...lab.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE);if(nodes.length)nodes[nodes.length-1].textContent=' '+text}}if(!$q('#cfSemantics493')){const x=document.createElement('p');x.id='cfSemantics493';x.className='help';x.textContent='PP・ExPP・EP・SEPは「次に動く側」の資源です。バルバロス／ゼタベア欄は自分の既知手札です。相手手番の枝はリーサル検証へ直接送らず、自分手番の子枝を作ってから送ります。';p.querySelector('p.help')?.insertAdjacentElement('afterend',x)}if(window.__wbCounterfactualV1?.protocol)window.__wbCounterfactualV1.protocol.resourceSemantics='pp/extraPPAvailable/epAvailable/sepAvailable are resources of state.sideToAct; hand fields describe the reviewed player own known hand.';return true}
  function updater(){const old=$q('#wbForceLatest463')||$q('#wbForceLatest462');if(!old)return false;if(old.dataset.wb493==='1')return true;const b=old.cloneNode(true);b.dataset.wb493='1';b.dataset.wb492='1';old.replaceWith(b);const st=$q('#wbUpdateStatus463')||$q('#wbUpdateStatus462');if(st)st.textContent='v4.9.3 / 分岐資源・表示修正版';b.addEventListener('click',async()=>{if(b.disabled)return;b.disabled=true;if(st)st.textContent='最新版を確認中…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js?v=4.9.3-20260915-13b',{updateViaCache:'none'});await reg.update()}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('wb-review-')&&k!=='wb-review-v4-9-3-20260915-13b').map(k=>caches.delete(k)))}if(st)st.textContent='更新完了。v4.9.3で再起動します…';setTimeout(()=>{const u=new URL(location.href);u.searchParams.set('latest','493b-'+Date.now());u.hash='';location.replace(u.href)},180)}catch(err){if(st)st.textContent='更新確認に失敗しました。';b.disabled=false;safeLog('force-latest-error-v493',{message:err?.message||String(err)})}});return true}
  let n=0;const tm=setInterval(()=>{n++;document.documentElement.dataset.wbLatestUi='493';relabel();updater();const h=$q('header h1'),s=$q('header p');if(h)h.textContent='シャドバWB リプレイ診断 v4.9.3';if(s)s.textContent='Build 2026.09.15-13b / 分岐資源の意味・最新版表示を修正';if(n>600)clearInterval(tm)},120);
  safeLog('patch-v493-active',{feature:'branch-resource-semantics-and-latest-ui-owner'});
})();
