(()=>{
  const PATCH='4.8.1-20260915-09';
  const $q=s=>document.querySelector(s);
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  function ensureZip(){if(window.JSZip)return Promise.resolve(window.JSZip);return new Promise((res,rej)=>{const old=document.querySelector('script[data-jszip-v481]');if(old){old.addEventListener('load',()=>window.JSZip?res(window.JSZip):rej(new Error('ZIP初期化失敗')),{once:true});return}const s=document.createElement('script');s.dataset.jszipV481='1';s.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';s.onload=()=>window.JSZip?res(window.JSZip):rej(new Error('ZIP初期化失敗'));s.onerror=()=>rej(new Error('ZIPライブラリ読込失敗'));document.head.appendChild(s)})}
  function installHook(){const Z=window.JSZip;if(!Z?.prototype?.generateAsync)return false;if(Z.prototype.__wbLethal481)return true;const original=Z.prototype.generateAsync;Z.prototype.generateAsync=async function(...args){try{const f=this.files?.['range-review.json'];if(f){const raw=await f.async('string'),m=JSON.parse(raw);m.analysisEngineV2=window.__wbCoachV2||null;m.lethalStateV2=window.__wbLethalV2||null;m.reviewProtocolV2={order:['公開情報の時間整合性を確認','そのターンの全リーサル候補を列挙','相手の確定/準確定返しを確認','実戦ルートと代替ルートを比較','短評と評価を出す'],hardRules:['リーサル候補を1本見つけても探索を止めない','主要資源が不明ならリーサルなしと断定しない','反実仮想は分岐直前から独立再計算する','相手が別行動を選べる場合は複数分岐を維持する']};m.reviewRequest=m.reviewRequest||{};m.reviewRequest.objective='公開情報の時間軸を守り、各自分ターンで主要リーサル候補を全探索してから短評する。最大の改善点は1つに絞る。';this.file('range-review.json',JSON.stringify(m,null,2));safeLog('lethal-context-embedded-v481',{snapshots:m.lethalStateV2?.snapshots?.length||0})}}catch(e){safeLog('lethal-context-embed-error-v481',{message:e?.message||String(e)})}return original.apply(this,args)};Object.defineProperty(Z.prototype,'__wbLethal481',{value:true});return true}
  function wrapButton(id){const b=$q(id);if(!b||b.dataset.wb481==='1')return false;const old=b.onclick;if(typeof old!=='function')return false;b.dataset.wb481='1';b.onclick=async e=>{try{await ensureZip();installHook()}catch(err){safeLog('lethal-prezip-error-v481',{message:err?.message||String(err)})}return old.call(b,e)};return true}
  function addNotice(){const p=$q('#lethalPanel480');if(!p||$q('#leZipNotice481'))return false;const n=document.createElement('p');n.id='leZipNotice481';n.className='help';n.textContent='保存したリーサル検証状態は、全試合ZIP・範囲ZIPの range-review.json に自動で埋め込みます。';p.appendChild(n);return true}
  function updater(){const old=$q('#wbForceLatest463')||$q('#wbForceLatest462');if(!old||old.dataset.wb481==='1')return false;const b=old.cloneNode(true);b.dataset.wb481='1';old.replaceWith(b);const st=$q('#wbUpdateStatus463')||$q('#wbUpdateStatus462');if(st)st.textContent='v4.8.1 / リーサル全探索ZIP連携';b.addEventListener('click',async()=>{if(b.disabled)return;b.disabled=true;if(st)st.textContent='最新版を確認中…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js?v=4.8.1-20260915-09',{updateViaCache:'none'});await reg.update()}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('wb-review-')&&k!=='wb-review-v4-8-1-20260915-09').map(k=>caches.delete(k)))}if(st)st.textContent='更新完了。v4.8.1で再起動します…';setTimeout(()=>{const u=new URL(location.href);u.searchParams.set('latest','481-'+Date.now());u.hash='';location.replace(u.href)},180)}catch(err){if(st)st.textContent='更新確認に失敗しました。';b.disabled=false;safeLog('force-latest-error-v481',{message:err?.message||String(err)})}});return true}
  let n=0;const tm=setInterval(()=>{n++;if(window.JSZip)installHook();wrapButton('#exportFullMatch465');wrapButton('#exportRange462');addNotice();updater();const h=$q('header h1'),s=$q('header p');if(h)h.textContent='シャドバWB リプレイ診断 v4.8.1';if(s)s.textContent='Build 2026.09.15-09 / リーサル全探索 v2 + ZIP連携';if(n>400)clearInterval(tm)},120);
  safeLog('patch-v481-active',{feature:'lethal-engine-direct-zip-bridge'});
})();