(()=>{
  const PATCH='4.9.1-20260915-11';
  const $q=s=>document.querySelector(s);
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  function ensureZip(){if(window.JSZip)return Promise.resolve(window.JSZip);return new Promise((res,rej)=>{const old=document.querySelector('script[data-jszip-v491]');if(old){old.addEventListener('load',()=>window.JSZip?res(window.JSZip):rej(new Error('ZIP初期化失敗')),{once:true});return}const s=document.createElement('script');s.dataset.jszipV491='1';s.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';s.onload=()=>window.JSZip?res(window.JSZip):rej(new Error('ZIP初期化失敗'));s.onerror=()=>rej(new Error('ZIPライブラリ読込失敗'));document.head.appendChild(s)})}
  function installHook(){const Z=window.JSZip;if(!Z?.prototype?.generateAsync)return false;if(Z.prototype.__wbCounterfactual491)return true;const original=Z.prototype.generateAsync;Z.prototype.generateAsync=async function(...args){try{const f=this.files?.['range-review.json'];if(f){const raw=await f.async('string'),m=JSON.parse(raw),tree=window.__wbCounterfactualV1||null;m.counterfactualTreeV1=tree;m.reviewProtocolV2=m.reviewProtocolV2||{};m.reviewProtocolV2.counterfactualRules=['各枝を独立した局面状態として評価する','実戦最終HPから単純差し引きして別枝を作らない','相手が別行動を選べる場合は兄弟枝として両方残す','各枝でリーサル探索を再実行する','knowledgeCutoffSecondsより後の公開情報を過去枝の既知情報にしない'];this.file('range-review.json',JSON.stringify(m,null,2));safeLog('counterfactual-tree-embedded-v491',{branches:tree?.branches?.length||0})}}catch(e){safeLog('counterfactual-zip-error-v491',{message:e?.message||String(e)})}return original.apply(this,args)};Object.defineProperty(Z.prototype,'__wbCounterfactual491',{value:true});return true}
  function wrap(id){const b=$q(id);if(!b||b.dataset.wb491==='1')return false;const old=b.onclick;if(typeof old!=='function')return false;b.dataset.wb491='1';b.onclick=async e=>{try{await ensureZip();installHook()}catch(err){safeLog('counterfactual-prezip-error-v491',{message:err?.message||String(err)})}return old.call(b,e)};return true}
  function updater(){const old=$q('#wbForceLatest463')||$q('#wbForceLatest462');if(!old||old.dataset.wb491==='1')return false;const b=old.cloneNode(true);b.dataset.wb491='1';old.replaceWith(b);const st=$q('#wbUpdateStatus463')||$q('#wbUpdateStatus462');if(st)st.textContent='v4.9.1 / 分岐ZIP連携';b.addEventListener('click',async()=>{if(b.disabled)return;b.disabled=true;if(st)st.textContent='最新版を確認中…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js?v=4.9.1-20260915-11',{updateViaCache:'none'});await reg.update()}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('wb-review-')&&k!=='wb-review-v4-9-1-20260915-11').map(k=>caches.delete(k)))}if(st)st.textContent='更新完了。v4.9.1で再起動します…';setTimeout(()=>{const u=new URL(location.href);u.searchParams.set('latest','491-'+Date.now());u.hash='';location.replace(u.href)},180)}catch(err){if(st)st.textContent='更新確認に失敗しました。';b.disabled=false;safeLog('force-latest-error-v491',{message:err?.message||String(err)})}});return true}
  let n=0;const tm=setInterval(()=>{n++;if(window.JSZip)installHook();wrap('#exportFullMatch465');wrap('#exportRange462');updater();const h=$q('header h1'),s=$q('header p');if(h)h.textContent='シャドバWB リプレイ診断 v4.9.1';if(s)s.textContent='Build 2026.09.15-11 / 反実仮想分岐 + ZIP確実連携';if(n>420)clearInterval(tm)},120);
  safeLog('patch-v491-active',{feature:'counterfactual-direct-zip-bridge'});
})();
