(()=>{
  const PATCH='4.10.8-20260916-20a';
  const $q=s=>document.querySelector(s);
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  const RESOURCE_IDS={extra:'#leExtra480',ep:'#leEp480',sep:'#leSep480'};
  let baseFill=null,baseCalc=null,baseSave=null,fillHandler=null,calcHandler=null,saveHandler=null;

  function videoEl(){return typeof video!=='undefined'?video:$q('#video')}
  function targetSide(){const s=$q('#targetSide')?.value;return s==='top'||s==='bottom'?s:'bottom'}
  function playOrder(){return $q('#playOrder')?.value==='先攻'?'先攻':'後攻'}
  function currentTurn(){const v=videoEl(),t=Number(v?.currentTime),rows=Array.isArray(window.turnTimeline39)?window.turnTimeline39:[];let row=null;if(Number.isFinite(t))for(const r of rows){if(Number(r.time)<=t&&(!row||Number(r.time)>Number(row.time)))row=r}return Number(row?.turn)||Number($q('#leTurn480')?.value)||null}
  function eligibility(turn){const first=playOrder()==='先攻';return{ep:!!turn&&turn>=(first?5:4),sep:!!turn&&turn>=(first?7:6)}}
  function drawFrame(){const v=videoEl();if(!v?.videoWidth||!v?.videoHeight)return null;const c=document.createElement('canvas');c.width=1200;c.height=Math.max(1,Math.round(c.width*v.videoHeight/v.videoWidth));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);return{c,x}}
  function rgbToHsv255(R,G,B){const r=R/255,g=G/255,b=B/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return{h,s:max?d/max:0,v:max}}
  function detectExtraButton(){if(playOrder()==='先攻')return{known:true,available:false,reason:'first-player-rule',method:'rule'};const f=drawFrame();if(!f)return{known:false,available:null,reason:'frame-missing',method:'image'};const side=targetSide(),r=side==='bottom'?{x0:.79,x1:.93,y0:.67,y1:.75}:{x0:.79,x1:.93,y0:.13,y1:.22};const sx=Math.max(0,Math.floor(r.x0*f.c.width)),sy=Math.max(0,Math.floor(r.y0*f.c.height)),sw=Math.max(1,Math.floor((r.x1-r.x0)*f.c.width)),sh=Math.max(1,Math.floor((r.y1-r.y0)*f.c.height));const d=f.x.getImageData(sx,sy,sw,sh).data;let n=0,orange=0,bright=0,sumV=0,sumS=0;for(let i=0;i<d.length;i+=4){const z=rgbToHsv255(d[i],d[i+1],d[i+2]);n++;sumV+=z.v;sumS+=z.s;if(z.h>=10&&z.h<=70&&z.s>=.39&&z.v>=.47)orange++;if(z.v>=.51&&z.s>=.31)bright++}const stats={orangeFrac:n?orange/n:0,brightFrac:n?bright/n:0,meanV:n?sumV/n:0,meanS:n?sumS/n:0};const available=stats.orangeFrac>=.25&&stats.brightFrac>=.30&&stats.meanV>=.47;return{known:available,available:available?true:null,reason:available?'bright-orange-button':'not-confidently-available',method:'image',side,stats:Object.fromEntries(Object.entries(stats).map(([k,v])=>[k,+v.toFixed(3)]))}}
  function tracked(key){const el=$q(RESOURCE_IDS[key]);return el?el.dataset.wbResourceSource4108||'unknown':'missing'}
  function markKnown(key,value,source){const el=$q(RESOURCE_IDS[key]);if(!el)return false;el.checked=!!value;el.indeterminate=false;el.dataset.wbResourceSource4108=source;return true}
  function markUnknown(key,source='unknown'){const el=$q(RESOURCE_IDS[key]);if(!el)return false;el.checked=false;el.indeterminate=true;el.dataset.wbResourceSource4108=source;return true}
  function ensureTracking(){for(const [key,sel] of Object.entries(RESOURCE_IDS)){const el=$q(sel);if(!el)continue;if(el.dataset.wbResourceTracking4108==='1')continue;el.dataset.wbResourceTracking4108='1';el.dataset.wbResourceSource4108=el.checked?'preexisting-manual':'unknown';el.indeterminate=!el.checked;el.addEventListener('change',()=>{el.indeterminate=false;el.dataset.wbResourceSource4108='manual';setTimeout(applyUnknownWarning,0)})}}
  function unknownResources(){const out=[];for(const [key,sel] of Object.entries(RESOURCE_IDS)){const el=$q(sel);if(el?.indeterminate)out.push(key==='extra'?'Extra PP':key.toUpperCase())}return out}
  function applyUnknownWarning(){const out=$q('#leResult480'),u=unknownResources();if(!out)return u;const marker='\n⚠ 資源未確認：';const base=String(out.textContent||'').split(marker)[0];out.textContent=base+(u.length?`${marker}${u.join(' / ')}\n→ 未確認資源を使うルートが残るため「リーサルなし」と断定禁止`:'');return u}
  function setStatus(msg,color='#9aa8bf'){const st=$q('#leStatus480');if(st){st.textContent=msg;st.style.color=color}}
  function updateEligibilityDefaults(){ensureTracking();const turn=currentTurn(),e=eligibility(turn),ep=$q(RESOURCE_IDS.ep),sep=$q(RESOURCE_IDS.sep);if(ep&&tracked('ep')!=='manual'&&tracked('ep')!=='preexisting-manual'){e.ep?markUnknown('ep','eligible-unrecognized'):markKnown('ep',false,'not-yet-eligible-rule')}if(sep&&tracked('sep')!=='manual'&&tracked('sep')!=='preexisting-manual'){e.sep?markUnknown('sep','eligible-unrecognized'):markKnown('sep',false,'not-yet-eligible-rule')}return{turn,...e}}
  function applyExtraDetection(){ensureTracking();const el=$q(RESOURCE_IDS.extra);if(!el)return{known:false,reason:'missing-control'};const source=tracked('extra'),manual=source==='manual'||source==='preexisting-manual';const result=detectExtraButton();if(!manual){if(result.known)markKnown('extra',!!result.available,result.reason);else markUnknown('extra',result.reason)}return{...result,manualPreserved:manual,uiKnown:!el.indeterminate,uiValue:el.indeterminate?null:el.checked}}
  function install(){const fill=$q('#leFill480'),calc=$q('#leCalc480'),save=$q('#leSave480');if(!fill||!calc||!save)return false;ensureTracking();if(fill.onclick!==fillHandler&&typeof fill.onclick==='function')baseFill=fill.onclick;if(calc.onclick!==calcHandler&&typeof calc.onclick==='function')baseCalc=calc.onclick;if(save.onclick!==saveHandler&&typeof save.onclick==='function')baseSave=save.onclick;if(!fillHandler)fillHandler=async e=>{if(fill.disabled)return;if(typeof baseFill==='function')await baseFill.call(fill,e);const elig=updateEligibilityDefaults(),extra=applyExtraDetection(),u=applyUnknownWarning();window.__wbResourceState4108={patch:PATCH,at:new Date().toISOString(),time:+(Number(videoEl()?.currentTime)||0).toFixed(3),turn:elig.turn,playOrder:playOrder(),targetSide:targetSide(),eligibility:elig,extra,unknown:u};safeLog('resource-state-read-v4108',window.__wbResourceState4108);if(u.length)setStatus(`PP・HP取得完了。${u.join(' / ')} は未確認です。`,'#facc15')};if(!calcHandler)calcHandler=e=>{let r;if(typeof baseCalc==='function')r=baseCalc.call(calc,e);applyUnknownWarning();return r};if(!saveHandler)saveHandler=e=>{const u=unknownResources();if(u.length){setStatus(`保存しません：${u.join(' / ')} が未確認です。`,'#facc15');applyUnknownWarning();safeLog('lethal-save-blocked-unknown-resource-v4108',{unknown:u});return}return typeof baseSave==='function'?baseSave.call(save,e):undefined};fill.onclick=fillHandler;calc.onclick=calcHandler;save.onclick=saveHandler;fill.textContent='動画位置からターン・PP・相手HP・資源取得';fill.dataset.wbState4108='1';updateEligibilityDefaults();applyUnknownWarning();return true}
  function note(){const p=$q('#lethalPanel480');if(!p||$q('#leResourceNote4108'))return false;const n=document.createElement('p');n.id='leResourceNote4108';n.className='help';n.textContent='Extra PP・EP・SEPは「未確認」と「使用不可」を区別します。灰色の中間状態は未確認です。未確認資源がある状態ではリーサル状態を保存しません。Extra PPは先攻なら使用不可、後攻では橙色のPP+1ボタンを高確信度で確認できた場合だけ使用可を自動入力します。';p.appendChild(n);return true}
  function latestUi(){window.__wbUiFinalVersion='4.10.8';document.documentElement.dataset.wbLatestUi='4108';let s=$q('#wbUiFinal4108');if(!s){s=document.createElement('style');s.id='wbUiFinal4108';document.head.appendChild(s)}s.textContent="header h1::after{content:'シャドバWB リプレイ診断 v4.10.8' !important}header>p:first-of-type::after{content:'Build 2026.09.16-20 / 資源の未確認状態を安全化' !important}";const st=$q('#wbUpdateStatus4104');if(st)st.textContent='v4.10.8 / Extra PP・EP・SEP安全化';const old=$q('#wbForceLatest4104');if(old&&old.dataset.wb4108!=='1'){const b=old.cloneNode(true);b.dataset.wb4108='1';old.replaceWith(b);b.addEventListener('click',async()=>{const x=$q('#wbUpdateStatus4104');if(b.disabled)return;b.disabled=true;if(x)x.textContent='最新版を確認中…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js?v=4.10.8-20260916-20a',{updateViaCache:'none'});await reg.update()}if('caches'in window){const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith('wb-review-')&&k!=='wb-review-v4-10-8-20260916-32').map(k=>caches.delete(k)))}if(x)x.textContent='更新完了。v4.10.8で再起動します…';setTimeout(()=>{const u=new URL(location.href);u.searchParams.set('latest','4108-'+Date.now());u.hash='';location.replace(u.href)},180)}catch(err){if(x)x.textContent='更新確認に失敗しました。';b.disabled=false;safeLog('force-latest-error-v4108',{message:err?.message||String(err)})}})}}
  function verify(){const f=$q('#leFill480'),c=$q('#leCalc480'),s=$q('#leSave480');const state={patch:PATCH,mounted:!!f,fillHandlerOk:!f||f.onclick===fillHandler,calcHandlerOk:!c||c.onclick===calcHandler,saveHandlerOk:!s||s.onclick===saveHandler,unknown:unknownResources(),checkedAt:new Date().toISOString()};state.ok=state.fillHandlerOk&&state.calcHandlerOk&&state.saveHandlerOk;window.__wbResourceSafety4108=state;safeLog('resource-state-invariant-v4108',state);return state.ok}
  $q('#videoFile')?.addEventListener('change',()=>{for(const key of Object.keys(RESOURCE_IDS)){const el=$q(RESOURCE_IDS[key]);if(el&&tracked(key)!=='manual'&&tracked(key)!=='preexisting-manual')markUnknown(key,'video-change')}window.__wbResourceState4108=null});
  let tries=0,stable=0;const tm=setInterval(()=>{tries++;latestUi();const ok=install();note();stable=ok?stable+1:0;if(tries%10===0)verify();if(stable>=8&&tries>25||tries>45)clearInterval(tm)},120);
  [80,400,1200,2600,4200,5600,6400,7200,8800,9800].forEach(ms=>setTimeout(()=>{latestUi();install();note();verify()},ms));
  window.__wbResourceRecognizer4108={detectExtraButton,eligibility,unknownResources,verify};safeLog('patch-v4108-active',{feature:'tri-state-resource-safety-extra-pp-positive-detection'});
})();
