(()=>{
  const PATCH='4.6.5-20260914-32';
  const $q=s=>document.querySelector(s);
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  const v=()=>typeof video!=='undefined'?video:$q('#video');
  const fmt2=s=>{try{return fmt(s)}catch{return Number(s).toFixed(1)+'s'}};
  const safeName=s=>String(s||'replay').replace(/\.[^.]+$/,'').replace(/[^\w\u3040-\u30ff\u3400-\u9fff-]+/g,'_').slice(0,54);
  const size=n=>n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;
  let busy=false,pendingFile=null;

  function ensureZip(){if(window.JSZip)return Promise.resolve(window.JSZip);return new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';s.onload=()=>window.JSZip?res(window.JSZip):rej(new Error('ZIP初期化失敗'));s.onerror=()=>rej(new Error('ZIPライブラリ読込失敗'));document.head.appendChild(s)})}
  async function seekSafe(t,reason='full-match-v465'){const vid=v();t=Math.max(0,Math.min(vid.duration-.05,t));if(Math.abs(vid.currentTime-t)>.025){if(typeof seek==='function')await seek(t,reason);else await new Promise((res,rej)=>{const done=()=>res();vid.addEventListener('seeked',done,{once:true});vid.currentTime=t;setTimeout(()=>rej(new Error('シーク失敗')),5000)})}await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))}
  function sig(){const src=frameCanvas(300),c=document.createElement('canvas');c.width=40;c.height=18;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data,a=new Uint8Array(c.width*c.height);let j=0;for(let i=0;i<d.length;i+=4)a[j++]=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);return a}
  const diff=(a,b)=>{if(!a||!b)return 0;let s=0;for(let i=0;i<a.length;i++)s+=Math.abs(a[i]-b[i]);return s/(a.length*255)};
  const med=a=>{if(!a.length)return 0;const b=a.slice().sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
  const pct=(a,p)=>{if(!a.length)return 0;const b=a.slice().sort((x,y)=>x-y);return b[Math.min(b.length-1,Math.max(0,Math.floor((b.length-1)*p)))]};
  const nearest=(rows,t)=>rows.reduce((best,r)=>!best||Math.abs(r.time-t)<Math.abs(best.time-t)?r:best,null);
  function merge(items,gap=.20){const a=items.slice().sort((x,y)=>x.time-y.time),out=[];for(const it of a){const last=out[out.length-1];if(last&&it.time-last.time<gap){if(it.priority>last.priority)out[out.length-1]=it}else out.push(it)}return out}
  function timeline(){return Array.isArray(window.turnTimeline39)?window.turnTimeline39.map(x=>({side:x.side,turn:Number(x.turn),time:Number(x.time)})).filter(x=>Number.isFinite(x.time)).sort((a,b)=>a.time-b.time):[]}
  function scanStep(duration){if(duration>900)return 4;if(duration>600)return 3;if(duration>300)return 2.5;return 2}

  async function selectFrames(start,end,status){
    const step=scanStep(end-start),rows=[];let prev=null,n=0;for(let t=start;t<=end+.001;t+=step){await seekSafe(t,'full-scan-v465');const s=sig(),d=prev?diff(prev,s):0;rows.push({time:+t.toFixed(3),diff:d});prev=s;n++;if(status)status.textContent=`試合全体を走査中… ${n}`}
    const ds=rows.slice(1).map(r=>r.diff),m=med(ds),mad=med(ds.map(x=>Math.abs(x-m))),thr=Math.max(.026,m+mad*1.9,pct(ds,.72)*.84),picks=[];const add=(time,priority,reason,d=0)=>{if(Number.isFinite(time)&&time>=start-.05&&time<=end+.05)picks.push({time:+time.toFixed(3),priority,reason,diff:d})};
    add(start,160,'match-start');add(end,160,'match-end');const mt=Number(window.mulliganPreview442?.time);if(Number.isFinite(mt))add(mt,170,'mulligan');
    for(const a of timeline().filter(x=>x.time>=start-.1&&x.time<=end+.1)){add(a.time,155,`turn-${a.side}-${a.turn}`);add(a.time-.35,108,'before-turn');add(a.time+.35,108,'after-turn')}
    const heartbeat=Math.max(5,Math.min(9,(end-start)/32));for(let t=start;t<=end+.001;t+=heartbeat){const r=nearest(rows,t);if(r)add(r.time,48,'continuity',r.diff)}
    for(let i=1;i<rows.length;i++){const c=rows[i].diff,p=rows[i-1]?.diff??0,nx=rows[i+1]?.diff??0;if(c>=thr&&c>=p&&c>=nx){add(rows[i-1].time,86+c*110,'before-change',c);add(rows[i].time,94+c*125,'change',c)}}
    for(const r of rows.slice(1).sort((a,b)=>b.diff-a.diff).slice(0,18))add(r.time,82+r.diff*100,'strong-change',r.diff);
    let selected=merge(picks);const MAX=60;if(selected.length>MAX){const must=selected.filter(x=>x.priority>=150),rest=selected.filter(x=>x.priority<150).sort((a,b)=>b.priority-a.priority||b.diff-a.diff).slice(0,Math.max(0,MAX-must.length));selected=merge([...must,...rest]).sort((a,b)=>a.time-b.time)}return{rows,selected,threshold:+thr.toFixed(4),step};
  }

  function mount(){
    if($q('#fullMatchPanel465'))return true;const anchor=$q('#rangeReviewPanel462')||$q('#capture')?.closest('.panel');if(!anchor?.parentNode)return false;
    const p=document.createElement('section');p.id='fullMatchPanel465';p.className='panel';p.innerHTML=`<h2>試合全体を短評</h2><p class="help">マリガンから試合終了まで、ターン境界と重要な盤面変化だけを抽出してZIPにします。既存の「最大5ターン」診断はそのまま使えます。</p><label>見てほしいこと（任意）<textarea id="fullMatchNote465" placeholder="例：全体を通して勝ち筋・打点温存・リーサル判断を短評してほしい"></textarea></label><div class="buttons"><button id="exportFullMatch465" class="good">試合全体の短評ZIPを作る</button></div><p id="fullMatchStatus465" class="help">動画を読み込んだら実行できます。</p><div id="fullMatchDetail465" class="ocrRead">最大60枚 / 横1000px / JPEG 62%</div><div id="fullMatchSave465" style="display:none;margin-top:12px;padding:12px;border:1px solid rgba(255,255,255,.15);border-radius:10px"><div id="fullMatchSaveInfo465" class="help"></div><div class="buttons"><button id="fullMatchSaveBtn465" class="good">ZIPをファイルに保存</button><button id="fullMatchDiscard465">破棄</button></div></div>`;anchor.parentNode.insertBefore(p,anchor.nextSibling);
    $q('#exportFullMatch465')?.addEventListener('click',exportFull);$q('#fullMatchSaveBtn465')?.addEventListener('click',savePending);$q('#fullMatchDiscard465')?.addEventListener('click',()=>{pendingFile=null;$q('#fullMatchSave465').style.display='none';});return true;
  }

  async function exportFull(){
    const vid=v(),status=$q('#fullMatchStatus465'),btn=$q('#exportFullMatch465');if(busy)return;if(!vid?.src||!Number.isFinite(vid.duration)||vid.duration<=1){if(status)status.textContent='先にリプレイ動画を読み込んでください。';return}busy=true;btn.disabled=true;pendingFile=null;$q('#fullMatchSave465').style.display='none';const orig=vid.currentTime;vid.pause();const started=performance.now();
    try{const JSZip=await ensureZip(),zip=new JSZip(),mt=Number(window.mulliganPreview442?.time),start=Number.isFinite(mt)?Math.max(.1,mt-.8):.1,end=Math.max(start+.5,vid.duration-.15);if(status)status.textContent='試合全体の重要場面を選んでいます…';const sel=await selectFrames(start,end,status);
      const manifest={format:'shadowverse-wb-full-match-review-v4.6.5',build:PATCH,mode:'full-match-short-review',source:typeof videoName!=='undefined'?videoName:'replay',createdAt:new Date().toISOString(),deck:$q('#deck')?.value||'',matchup:$q('#matchup')?.value||'',classDetection:window.classDetection442||null,mulliganPreview:window.mulliganPreview442||null,knownTurnTimeline:timeline(),reviewRequest:{objective:'試合全体を短評し、勝率向上につながる最大の改善点を1つ特定する',note:$q('#fullMatchNote465')?.value||'',output:['マリガン短評','各自分ターンを◎○△×で短評','重要な相手ターンのみ補足','試合全体の総評','最大の改善点1つ','該当する学習タグ'],caution:'11T以降は最大PP=10のためターン番号ラベルを自動確定しない。画像時系列から評価する。'},fullMatch:{analysisStartTimeSeconds:+start.toFixed(3),analysisEndTimeSeconds:+end.toFixed(3),durationSeconds:+vid.duration.toFixed(3),scanStepSeconds:sel.step,changeThreshold:sel.threshold,frames:[]}};
      let done=0;for(const it of sel.selected){await seekSafe(it.time,'full-capture-v465');const c=frameCanvas(1000),blob=await canvasBlob(c,.62),file=`full-match/frames/frame-${String(done+1).padStart(3,'0')}-${it.time.toFixed(2)}s.jpg`;zip.file(file,blob,{compression:'STORE'});manifest.fullMatch.frames.push({file,timeSeconds:it.time,reason:it.reason,diff:+(it.diff||0).toFixed(4)});done++;if(status)status.textContent=`重要画像を保存中… ${done}/${sel.selected.length}`}
      zip.file('range-review.json',JSON.stringify(manifest,null,2));zip.file('README.txt','Shadowverse WB 試合全体短評 v4.6.5\nマリガン〜試合終了までの重要場面を抽出しています。\nChatGPTにはZIPごと添付してください。\n');if(status)status.textContent='ZIPを仕上げています…';const blob=await zip.generateAsync({type:'blob',compression:'STORE'}),name=`${safeName(typeof videoName!=='undefined'?videoName:'replay')}-full-match-review-v4.6.5.zip`;pendingFile=new File([blob],name,{type:'application/zip',lastModified:Date.now()});$q('#fullMatchSaveInfo465').textContent=`ZIP準備完了：${name}（${size(pendingFile.size)}） / ${sel.rows.length}枚走査 → ${sel.selected.length}枚保存 / 約${((performance.now()-started)/1000).toFixed(1)}秒`;$q('#fullMatchSave465').style.display='block';if(status)status.textContent='試合全体ZIPを作成しました。保存してChatGPTへ添付してください。';safeLog('full-match-ready-v465',{size:pendingFile.size,scanFrames:sel.rows.length,selectedFrames:sel.selected.length,duration:vid.duration});
    }catch(e){if(status)status.textContent='試合全体ZIP作成失敗：'+(e?.message||String(e));safeLog('full-match-error-v465',{message:e?.message||String(e)})}finally{try{await seekSafe(orig,'full-return-v465')}catch{}busy=false;btn.disabled=false}
  }
  async function savePending(){const status=$q('#fullMatchStatus465');if(!pendingFile)return;try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[pendingFile]}))){await navigator.share({files:[pendingFile],title:'Shadowverse WB 試合全体短評ZIP'});if(status)status.textContent='共有シートを開きました。「ファイルに保存」を選んでください。'}else if(status)status.textContent='この環境ではファイル保存用共有シートを利用できません。';}catch(e){if(e?.name==='AbortError'){if(status)status.textContent='保存をキャンセルしました。ZIPは残っています。';return}if(status)status.textContent='保存画面を開けませんでした：'+(e?.message||String(e))}}

  let tries=0;const timer=setInterval(()=>{tries++;if(mount()||tries>100)clearInterval(timer)},150);const header=$q('header h1'),sub=$q('header p');if(header)header.textContent='シャドバWB リプレイ診断 v4.6.5';if(sub)sub.textContent='Build 2026.09.14-32 / 試合全体短評 + ナイトメア判定改善';safeLog('patch-v465-active',{feature:'full-match-short-review'});
})();