(()=>{
const PATCH='4.10.8.6-20260917-20o';
const $q=s=>document.querySelector(s);
const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
let finalKey='',pipelineBusy=false,mulliganBusy=false,finalClassKey='',finalClassState=null;
function videoEl(){return typeof video!=='undefined'?video:$q('#video')}
function videoKey(){const f=$q('#videoFile')?.files?.[0];if(f)return`${f.name}|${f.size}|${f.lastModified}`;const v=videoEl();return String(v?.currentSrc||v?.src||'no-video')}
function installSeekGuard(){const base=window.seek;if(typeof base!=='function'||base.__wb41086)return false;const wrapped=async function(t,reason='seek'){const r=String(reason||'');const legacyClass=r==='class-anchor-v468'||r==='class-recheck-v464';const blockedPreview=r==='preview-v442'&&(window.__wbTurnValidationPending41085||window.__wbTurnValidationBusy41085||window.__wbTurnPostProcessPending41085);if(legacyClass||blockedPreview){safeLog('legacy-seek-suppressed-v41086',{reason:r,target:Number(t),validationPending:!!window.__wbTurnValidationPending41085,validationBusy:!!window.__wbTurnValidationBusy41085,postPending:!!window.__wbTurnPostProcessPending41085});return}return base(t,reason)};wrapped.__wb41086=true;wrapped.__wbBase=base;window.seek=wrapped;return true}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return{h,s:max?d/max:0,v:max}}
async function settle(){await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))}
async function seekSafe(t){const v=videoEl();if(!v||!Number.isFinite(v.duration))throw Error('動画未読込');t=Math.max(0,Math.min(v.duration-.05,Number(t)||0));if(Math.abs(v.currentTime-t)>.025){if(typeof seek==='function')await seek(t,'mulligan-final-v41086');else{v.currentTime=t;await new Promise(res=>v.addEventListener('seeked',res,{once:true}))}}await settle()}
function cardSlotScore(src,cx){const x0=Math.max(0,Math.floor(src.width*(cx-.043))),x1=Math.min(src.width,Math.ceil(src.width*(cx+.043))),y0=Math.floor(src.height*.49),y1=Math.min(src.height,Math.ceil(src.height*.84)),ctx=src.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(x0,y0,Math.max(1,x1-x0),Math.max(1,y1-y0)),d=im.data;let n=0,color=0,sum=0,sum2=0,edges=0,prev=null,w=im.width;for(let y=1;y<im.height-1;y+=3){for(let x=1;x<im.width-1;x+=3){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2],lum=.299*r+.587*g+.114*b,h=rgbToHsv(r,g,b);n++;sum+=lum;sum2+=lum*lum;if(h.s>.18&&h.v>.24)color++;if(prev!==null&&Math.abs(lum-prev)>34)edges++;prev=lum}}if(!n)return{occupied:false,score:0};const mean=sum/n,std=Math.sqrt(Math.max(0,sum2/n-mean*mean)),colorRatio=color/n,edgeRatio=edges/Math.max(1,n-1),score=colorRatio*.48+Math.min(1,std/68)*.32+Math.min(1,edgeRatio/.30)*.20;return{occupied:score>.40&&colorRatio>.20,score:+score.toFixed(3)}}
function handScore(src){const centers=[.305,.425,.545,.665],slots=centers.map(x=>cardSlotScore(src,x));return{count:slots.filter(x=>x.occupied).length,total:+slots.reduce((s,x)=>s+x.score,0).toFixed(3)}}
function firstFourRun(rows){let run=[];for(const r of rows){if(r.handCount===4)run.push(r);else if(run.length){if(run.length>=2)return run;run=[]}}return run.length>=2?run:[]}
function plan(firstTurn){const v=videoEl(),start=Math.max(.5,firstTurn-8),end=Math.min(v.duration-.2,firstTurn-2),target=Math.max(start,Math.min(end,firstTurn-3)),times=[];for(let t=start;t<=end+.001&&times.length<30;t+=.5)times.push(+t.toFixed(2));return{firstTurn,start,end,target,times}}
function copyFrame(src){const c=document.createElement('canvas');c.width=src.width;c.height=src.height;c.getContext('2d').drawImage(src,0,0);return c}
async function buildMulligan(firstTurnOverride=null,reason='final-turn'){
if(mulliganBusy)return window.mulliganPreview442||null;const v=videoEl(),key=videoKey(),firstTurn=Number.isFinite(Number(firstTurnOverride))?Number(firstTurnOverride):Number(window.turnTimeline39?.[0]?.time);if(!v?.src||!Number.isFinite(v.duration)||!Number.isFinite(firstTurn))return null;mulliganBusy=true;window.__wbMulliganBusy41086=true;const original=Number(v.currentTime)||0,wasPaused=v.paused,still=$q('#mulliganStill442'),stillTime=$q('#mulliganStillTime442'),status=$q('#previewStatus442');v.pause();if(still)still.style.display='none';if(stillTime)stillTime.textContent='';if(status)status.textContent='確定した初回ターンからマリガン画像を取得中…';let result=null;
try{const p=plan(firstTurn),rows=[];for(const t of p.times){if(key!==videoKey())throw Error('video-changed');await seekSafe(t);const src=typeof frameCanvas==='function'?frameCanvas(1200):null;if(!src)continue;const hs=handScore(src);rows.push({time:t,handCount:hs.count,handScore:hs.total})}const run=firstFourRun(rows);let chosen;if(run.length)chosen=run.slice().sort((a,b)=>Math.abs(a.time-p.target)-Math.abs(b.time-p.target)||b.handScore-a.handScore)[0];else chosen=rows.slice().sort((a,b)=>b.handCount-a.handCount||Math.abs(a.time-p.target)-Math.abs(b.time-p.target)||b.handScore-a.handScore)[0];if(chosen){await seekSafe(chosen.time);const src=frameCanvas(1500),copy=copyFrame(src);if(still){still.src=copy.toDataURL('image/jpeg',.88);still.style.display='block'}if(stillTime)stillTime.textContent=`初期4枚：${typeof fmt==='function'?fmt(chosen.time):chosen.time.toFixed(1)} / 初回ターン ${typeof fmt==='function'?fmt(firstTurn):firstTurn.toFixed(1)}`;result={patch:PATCH,time:chosen.time,handCount:chosen.handCount,score:chosen.handScore,firstPP:null,firstTurn:+firstTurn.toFixed(3),targetTime:+p.target.toFixed(3),scanStart:+p.start.toFixed(3),scanEnd:+p.end.toFixed(3),run:run.map(r=>r.time),sampleCount:rows.length,reason};window.mulliganPreview442=result;if(status)status.textContent=chosen.handCount===4?'初回ターン直前の4枚表示区間から代表画像を選びました。':'4枚区間を確定できなかったため候補画像を表示しています。';safeLog('mulligan-preview-v41086',{...result,samples:rows})}}
catch(err){if(status)status.textContent='マリガン画像取得失敗：'+(err?.message||String(err));safeLog('mulligan-preview-error-v41086',{message:err?.message||String(err),reason})}
finally{try{if(key===videoKey())await seekSafe(original)}catch{}if(!wasPaused&&key===videoKey())try{await v.play()}catch{}mulliganBusy=false;window.__wbMulliganBusy41086=false}
return result;
}
async function validateClassAfterMulligan(reason='final-turn'){
const api=window.__wbResourceClass41084;if(!api?.validateDisplayedClass)return null;window.classDetection442=null;const r=await api.validateDisplayedClass('final-pipeline-v41086-'+reason);finalClassKey=videoKey();finalClassState=r?{...r}:null;api.enforceClassUi?.();if(!r?.accepted){const st=$q('#classStatus442');if(st)st.textContent='自動判定保留：VS画面未収録、またはクラスアイコンを確認できません。手動選択してください。'}return r;
}
async function runFinalPipeline(detail={}){
const key=videoKey();if(!key||pipelineBusy)return;if(finalKey===key&&window.mulliganPreview442&&Math.abs(Number(window.mulliganPreview442.firstTurn)-Number(detail.firstTurnTime))<.8)return;pipelineBusy=true;window.__wbTurnPostProcessPending41085=true;const firstTurn=Number(detail.firstTurnTime||window.turnTimeline39?.[0]?.time);let mull=null,cls=null;
try{mull=await buildMulligan(firstTurn,'turn-finalized');if(key===videoKey())cls=await validateClassAfterMulligan('turn-finalized');finalKey=key;safeLog('turn-postprocess-complete-v41086',{key,firstTurn,mulligan:!!mull,classAccepted:!!cls?.accepted,classCandidate:cls?.candidate||'',classMethod:cls?.method||''})}
catch(err){safeLog('turn-postprocess-error-v41086',{key,message:err?.message||String(err)})}
finally{pipelineBusy=false;window.__wbTurnPostProcessPending41085=false;window.__wbTurnValidator41085?.releaseUi?.('ターン解析・マリガン・クラス更新完了')}
}

function enforceFinalClassState(){const api=window.__wbResourceClass41084;if(!finalClassState||finalClassKey!==videoKey()||pipelineBusy||mulliganBusy)return;if(window.classDetection442?.patch!==finalClassState.patch||window.classDetection442?.candidate!==finalClassState.candidate||!!window.classDetection442?.accepted!==!!finalClassState.accepted)window.classDetection442={...finalClassState};api?.enforceClassUi?.()}
function installPreviewOwner(){const old=$q('#previewMulligan442');if(!old||old.dataset.wb41086==='1')return false;const b=old.cloneNode(true);b.dataset.wb41086='1';old.replaceWith(b);b.addEventListener('click',async e=>{e.preventDefault();const first=Number(window.turnTimeline39?.[0]?.time);await buildMulligan(first,'manual-reacquire');await validateClassAfterMulligan('manual-reacquire')});return true}
function buildStyle(){let s=$q('#wbUiFeature41086');if(!s){s=document.createElement('style');s.id='wbUiFeature41086';document.head.appendChild(s)}const css="header h1{font-size:0!important}header h1::after{content:'シャドバWB リプレイ診断 v4.10.8';font-size:18px!important;font-weight:700}header>p:first-of-type{font-size:0!important}header>p:first-of-type::after{content:'Build 2026.09.17-20o / ターン・マリガン・クラス直列化';font-size:12px!important;color:#9ba8bf}";if(s.textContent!==css)s.textContent=css}
function verify(){const st={patch:PATCH,seekGuard:!!window.seek?.__wb41086,previewOwner:$q('#previewMulligan442')?.dataset?.wb41086==='1',finalEventListener:true,legacyClassSeekSuppression:true,postprocessSerialized:true,finalClassGuard:true,checkedAt:new Date().toISOString()};st.ok=st.seekGuard&&st.finalEventListener;window.__wbPostProcessSafety41086=st;safeLog('postprocess-invariant-v41086',st);return st.ok}
installSeekGuard();buildStyle();installPreviewOwner();const tm=setInterval(()=>{buildStyle();installPreviewOwner();enforceFinalClassState();if(window.seek&&!window.seek.__wb41086)installSeekGuard()},250);setTimeout(()=>clearInterval(tm),20000);window.addEventListener('wb-turn-timeline-final-v41085',e=>setTimeout(()=>runFinalPipeline(e?.detail||{}),60));$q('#videoFile')?.addEventListener('change',()=>{finalKey='';pipelineBusy=false;mulliganBusy=false;finalClassKey='';finalClassState=null;window.__wbMulliganBusy41086=false});window.__wbPostProcess41086={buildMulligan,validateClassAfterMulligan,runFinalPipeline,verify};setTimeout(verify,2800);safeLog('patch-v41086-active',{feature:'serialized-mulligan-class-postprocess-legacy-seek-suppression'});
})();
