(()=>{
const PATCH='4.10.8.5-20260917-20n';
const $q=s=>document.querySelector(s);
const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
let runToken=0,activeKey='',validationDoneKey='';
function videoEl(){return typeof video!=='undefined'?video:$q('#video')}
function videoKey(){const f=$q('#videoFile')?.files?.[0];if(f)return`${f.name}|${f.size}|${f.lastModified}`;const v=videoEl();return String(v?.currentSrc||v?.src||'no-video')}
function targetSide(){const s=$q('#targetSide')?.value;return s==='top'||s==='bottom'?s:'bottom'}
function rgbToHsv(R,G,B){const r=R/255,g=G/255,b=B/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return{h,s:max?d/max:0,v:max}}
async function settle(){await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))}
async function seekFrame(t,reason='turn-validate-v41085'){
const v=videoEl();if(!v||!Number.isFinite(v.duration))return false;t=Math.max(.05,Math.min(v.duration-.08,Number(t)||.05));
try{if(Math.abs(v.currentTime-t)>.025){if(typeof seek==='function')await seek(t,reason);else await new Promise((res,rej)=>{let done=false;const on=()=>finish(true),to=setTimeout(()=>finish(false),3000);function finish(ok){if(done)return;done=true;v.removeEventListener('seeked',on);clearTimeout(to);ok?res():rej(Error('seek timeout'))}v.addEventListener('seeked',on,{once:true});v.currentTime=t})}await settle();return true}catch{return false}
}
function ppPoints(){try{if(typeof window.ppPoints==='object'&&window.ppPoints?.top&&window.ppPoints?.bottom)return window.ppPoints}catch{}return{top:{x:.8811,y:.2905},bottom:{x:.8822,y:.6065}}}
function drawFrame(){const v=videoEl();if(!v?.videoWidth||!v?.videoHeight)return null;const c=document.createElement('canvas');c.width=1200;c.height=Math.max(1,Math.round(c.width*v.videoHeight/v.videoWidth));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);return{c,x}}
function boardGreen(f){const pts=ppPoints(),vals=[];for(const p of [pts.top,pts.bottom]){const cx=Number(p?.x)||.882,cy=Number(p?.y)||.45,rx=.06,ry=.05,x0=Math.max(0,Math.floor((cx-rx)*f.c.width)),x1=Math.min(f.c.width,Math.ceil((cx+rx)*f.c.width)),y0=Math.max(0,Math.floor((cy-ry)*f.c.height)),y1=Math.min(f.c.height,Math.ceil((cy+ry)*f.c.height)),d=f.x.getImageData(x0,y0,Math.max(1,x1-x0),Math.max(1,y1-y0)).data;let n=0,g=0;for(let i=0;i<d.length;i+=4){const z=rgbToHsv(d[i],d[i+1],d[i+2]);n++;if(z.h>=70&&z.h<=180&&z.s>=.20&&z.v>=.15)g++}vals.push(n?g/n:0)}return{top:vals[0]||0,bottom:vals[1]||0,max:Math.max(vals[0]||0,vals[1]||0)}}
function indicatorSignal(){
const f=drawFrame();if(!f)return{side:null,visible:false,pixels:0,boardGreen:0};
const sx=Math.round(f.c.width*.82),sy=Math.round(f.c.height*.34),sw=Math.max(8,Math.round(f.c.width*.09)),sh=Math.max(8,Math.round(f.c.height*.21)),c=document.createElement('canvas');c.width=48;c.height=64;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(f.c,sx,sy,sw,sh,0,0,48,64);const d=x.getImageData(0,0,48,64).data,total=d.length/4;let red=0,blue=0,count=0,dark=0,white=0,gold=0;
for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx-mn;if(mx<60)dark++;if(mn>150&&sat<65)white++;if(r>120&&g>70&&g<190&&b<110&&r-b>50)gold++;if(mx<80||sat<40)continue;red+=Math.max(0,r-(b+g)/2);blue+=Math.max(0,b-(r+g)/2);count++}
const hud=boardGreen(f),boardOk=hud.max>=.08,visible=((dark/total>=.08&&(gold/total>=.008||white/total>=.012))||(gold/total>=.015&&white/total>=.012));if(!boardOk||!visible||count<900)return{side:null,diff:0,pixels:count,visible:false,boardGreen:+hud.max.toFixed(3)};const diff=(red-blue)/count,target=targetSide(),opponent=target==='top'?'bottom':'top',side=diff>15?opponent:diff<-15?target:null;return{side,diff:+diff.toFixed(2),pixels:count,visible:!!side,boardGreen:+hud.max.toFixed(3)}
}
function segmentsFromRows(rows,step){const raw=[];let cur=null;for(const r of rows.slice().sort((a,b)=>a.time-b.time)){if(!r.side)continue;if(cur&&cur.side===r.side&&r.time-cur.last<=step*2.1){cur.last=r.time;cur.count++}else{cur={side:r.side,start:r.time,last:r.time,count:1};raw.push(cur)}}const filtered=raw.filter(s=>s.count>=2),out=[];for(const s of filtered){if(out.length&&out[out.length-1].side===s.side){out[out.length-1].last=s.last;out[out.length-1].count+=s.count}else out.push({...s})}return out}
function stableLooksAligned(stable,segs){if(!Array.isArray(stable)||stable.length<4||segs.length<2)return false;for(let off=0;off<Math.min(4,stable.length-1);off++){const n=Math.min(4,segs.length,stable.length-off);if(n<2)continue;let ok=true;for(let i=0;i<n;i++){if(stable[off+i]?.side!==segs[i]?.side||Math.abs(Number(stable[off+i]?.time)-Number(segs[i]?.start))>2.5){ok=false;break}}if(ok)return true}return false}
function lockTurnUi(on,msg=''){const pick=$q('#turnPick'),go=$q('#goTurn'),st=$q('#scanStatus');if(pick)pick.disabled=!!on;if(go){if(on)go.disabled=true;else{const n=Number(pick?.value),has=!!(typeof turnMap==='object'&&turnMap?.[n]);go.disabled=!has}}if(st&&msg)st.textContent=msg}
function releaseUi(msg='ターン解析完了（HUD確認済み）'){window.__wbTurnPostProcessPending41085=false;lockTurnUi(false,msg)}
async function refineStart(seg,sample){let hi=Number(seg.start),lo=Math.max(.05,hi-.75);for(let i=0;i<5;i++){const mid=(lo+hi)/2,q=await sample(mid);if(q.side===seg.side)hi=q.time;else lo=q.time}return +Number(hi).toFixed(3)}
function makeEarlyTimeline(segs,starts){const counts={top:0,bottom:0};return segs.map((s,i)=>{counts[s.side]++;return{side:s.side,turn:counts[s.side],time:starts[i],source:'turn-indicator-board-validated-v4.10.8.5',confidence:92,raw:'',score:8,inferScore:null,indicatorOnly:true,boardValidated:true}})}
function findAnchor(stable,early,side){let best=null;for(const s of stable.filter(x=>x.side===side)){for(const e of early.filter(x=>x.side===side)){const d=Math.abs(Number(s.time)-Number(e.time)),offset=Number(e.turn)-Number(s.turn);if(d<=1.35&&offset>=0&&offset<=2&&(!best||d<best.d))best={d,stable:s,early:e,offset}}}return best}
function mergeEarlyWithStable(stable,early){const anchors={top:findAnchor(stable,early,'top'),bottom:findAnchor(stable,early,'bottom')};if(!anchors.top||!anchors.bottom)throw Error('early-stable-anchor-missing');if(anchors.top.offset!==anchors.bottom.offset)throw Error('side-offset-mismatch');const out=early.slice(),last={top:Math.max(...early.filter(x=>x.side==='top').map(x=>x.turn),0),bottom:Math.max(...early.filter(x=>x.side==='bottom').map(x=>x.turn),0)};for(const s of stable){const a=anchors[s.side];if(Number(s.time)<=Number(a.stable.time)+.8)continue;const turn=Number(s.turn)+a.offset;if(turn<=last[s.side])continue;out.push({...s,turn,time:+Number(s.time).toFixed(3),source:'stable-tail-shift-v4.10.8.5',confidence:Math.min(90,Number(s.confidence)||88),boardValidatedTail:true});last[s.side]=turn}out.sort((a,b)=>a.time-b.time);const next={top:1,bottom:1};for(let i=0;i<out.length;i++){const r=out[i];if(r.turn!==next[r.side])throw Error('turn-sequence-gap');next[r.side]++;if(i&&out[i-1].side===r.side)throw Error('non-alternating-merged-timeline')}return{timeline:out,anchors}}
function applyTimeline(timeline){const target=targetSide();window.turnTimeline39=timeline;window.rejectedTurns392=[];try{if(typeof turnMap!=='undefined'){for(const k of Object.keys(turnMap))delete turnMap[k];for(const r of timeline.filter(x=>x.side===target))turnMap[r.turn]={time:r.time,source:'pp-v4.10.8.5-board-validated',side:target,confidence:r.confidence||90,raw:String(r.turn)};if(typeof renderTurnMap==='function')renderTurnMap();if(typeof updateTurnPick==='function')updateTurnPick()}}catch(err){safeLog('turn-map-render-error-v41085',{message:err?.message||String(err)})}const el=$q('#turnTimeline39');if(el)el.textContent=timeline.map(r=>`${r.side==='top'?'上':'下'}${r.turn}T  ${typeof fmt==='function'?fmt(r.time):r.time.toFixed(2)}  ${r.boardValidated?'HUD確認済み':'補正済み'}`).join('\n');const play=$q('#playOrder');if(play&&timeline[0]){play.value=timeline[0].side===target?'先攻':'後攻';play.dispatchEvent(new Event('change',{bubbles:true}))}}
async function validateTimeline(detail={}){
const key=videoKey(),token=++runToken,v=videoEl();if(!key||!v?.videoWidth||!Number.isFinite(v.duration))return null;if(validationDoneKey===key)return window.turnTimeline39||null;if(activeKey===key)return null;activeKey=key;window.__wbTurnValidationPending41085=false;window.__wbTurnValidationBusy41085=true;window.__wbTurnPostProcessPending41085=true;lockTurnUi(true,'ターン最終確認中…');
const original=Number(v.currentTime)||0,wasPaused=v.paused;v.pause();const cache=new Map();let seeks=0,outcome=null;
const sample=async t=>{t=Math.max(.05,Math.min(v.duration-.08,Number(t)||.05));const k=t.toFixed(3);if(cache.has(k))return cache.get(k);if(token!==runToken||key!==videoKey())throw Error('cancelled');if(!await seekFrame(t)){const z={time:+k,side:null,pixels:0,boardGreen:0};cache.set(k,z);return z}seeks++;const z={time:+k,...indicatorSignal()};cache.set(k,z);return z};
try{
const stable=Array.isArray(window.turnTimeline39)?window.turnTimeline39.slice():[];if(stable.length<4)throw Error('stable-timeline-missing');const quick=[];const quickEnd=Math.min(22,v.duration-.08);for(let t=.5;t<=quickEnd+.001;t+=1)quick.push(await sample(t));const quickSegs=segmentsFromRows(quick,1);
if(stableLooksAligned(stable,quickSegs)){validationDoneKey=key;outcome={timeline:stable,corrected:false,seeks,oldTimeline:stable,quickSegments:quickSegs.slice(0,6),mode:'subsequence-aligned'};}
else{
const early=[];const end=Math.min(38,v.duration-.08);for(let t=.5;t<=end+.001;t+=.5)early.push(await sample(t));const segs=segmentsFromRows(early,.5);if(segs.length<4)throw Error('insufficient-early-hud-segments');const starts=[];for(const s of segs)starts.push(await refineStart(s,sample));const earlyTimeline=makeEarlyTimeline(segs,starts),merged=mergeEarlyWithStable(stable,earlyTimeline);applyTimeline(merged.timeline);validationDoneKey=key;outcome={timeline:merged.timeline,corrected:true,seeks,oldTimeline:stable,quickSegments:quickSegs.slice(0,6),earlySegments:segs,anchors:merged.anchors,mode:'early-only-correction'};
}
}catch(err){if(err?.message!=='cancelled'){safeLog('turn-timeline-validation-error-v41085',{key,message:err?.message||String(err),seeks});outcome={timeline:window.turnTimeline39||[],corrected:false,error:true,seeks,message:err?.message||String(err),mode:'fail-safe-stable'}}}
finally{try{if(key===videoKey())await seekFrame(original,'turn-validate-restore-v41085')}catch{}if(!wasPaused&&key===videoKey())try{await v.play()}catch{}window.__wbTurnValidationBusy41085=false;window.__wbTurnValidationPending41085=false;activeKey='';if(outcome&&key===videoKey()){const rec={patch:PATCH,key,corrected:!!outcome.corrected,error:!!outcome.error,seeks:outcome.seeks,mode:outcome.mode,oldTimeline:outcome.oldTimeline||null,quickSegments:outcome.quickSegments||[],earlySegments:outcome.earlySegments||null,anchors:outcome.anchors||null,timeline:outcome.timeline||[],checkedAt:new Date().toISOString()};window.__wbTurnTimelineValidation41085=rec;safeLog('turn-timeline-validation-v41085',rec);lockTurnUi(true,'ターン確定。マリガン・クラスを更新中…');window.dispatchEvent(new CustomEvent('wb-turn-timeline-final-v41085',{detail:{patch:PATCH,corrected:!!outcome.corrected,error:!!outcome.error,timeline:outcome.timeline||[],firstSide:outcome.timeline?.[0]?.side,firstTurnTime:outcome.timeline?.[0]?.time,key}}));setTimeout(()=>{if(window.__wbTurnPostProcessPending41085&&key===videoKey())releaseUi('ターン解析完了。後処理は手動再取得できます。')},12000)}else releaseUi('ターン解析の最終確認を完了できませんでした。')}
return outcome?.timeline||null;
}
function scheduleValidation(e){if(e?.detail?.patch===PATCH)return;const key=videoKey();if(!key||validationDoneKey===key||window.__wbTurnValidationPending41085||window.__wbTurnValidationBusy41085)return;window.__wbTurnValidationPending41085=true;window.__wbTurnPostProcessPending41085=true;lockTurnUi(true,'ターン最終確認を開始します…');setTimeout(async()=>{for(let i=0;i<80&&window.turnAnalysisBusy392;i++)await new Promise(r=>setTimeout(r,100));if(key===videoKey())await validateTimeline(e?.detail||{});else{window.__wbTurnValidationPending41085=false;releaseUi()}},80)}
function buildStyle(){let s=$q('#wbUiFeature41085');if(!s){s=document.createElement('style');s.id='wbUiFeature41085';document.head.appendChild(s)}const css="header h1{font-size:0!important}header h1::after{content:'シャドバWB リプレイ診断 v4.10.8';font-size:18px!important;font-weight:700}header>p:first-of-type{font-size:0!important}header>p:first-of-type::after{content:'Build 2026.09.17-20n / 軽量ターン検証 + 後処理直列化';font-size:12px!important;color:#9ba8bf}";if(s.textContent!==css)s.textContent=css}
function verify(){const st={patch:PATCH,listener:true,subsequenceAlignment:true,earlyOnlyCorrection:true,fullVideoRescan:false,interactionLock:true,stableScannerShaExpected:'8543ddc47c0b6648f4151a61d3a5d060eb39ba3f',validationDoneKey,checkedAt:new Date().toISOString()};st.ok=true;window.__wbTurnSafety41085=st;safeLog('turn-safety-invariant-v41085',st);return true}
buildStyle();setInterval(buildStyle,800);window.addEventListener('wb-turn-timeline-ready',scheduleValidation);$q('#videoFile')?.addEventListener('change',()=>{runToken++;activeKey='';validationDoneKey='';window.__wbTurnValidationPending41085=false;window.__wbTurnValidationBusy41085=false;window.__wbTurnPostProcessPending41085=false;window.__wbTurnTimelineValidation41085=null});window.__wbTurnValidator41085={validateTimeline,verify,releaseUi};setTimeout(verify,2500);safeLog('patch-v41085-active',{feature:'lightweight-subsequence-turn-validation-early-only-correction-serialized-postprocess'});
})();
