(()=>{
  const PATCH='4.6.5-20260914-33';
  const $q=s=>document.querySelector(s);
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  const v=()=>typeof video!=='undefined'?video:$q('#video');
  const safeName=s=>String(s||'replay').replace(/\.[^.]+$/,'').replace(/[^\w\u3040-\u30ff\u3400-\u9fff-]+/g,'_').slice(0,54);
  const size=n=>n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;
  let busy=false,pendingFile=null;
  function ensureZip(){if(window.JSZip)return Promise.resolve(window.JSZip);return new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';s.onload=()=>window.JSZip?res(window.JSZip):rej(new Error('ZIP初期化失敗'));s.onerror=()=>rej(new Error('ZIPライブラリ読込失敗'));document.head.appendChild(s)})}
  async function seekSafe(t,reason='full-match-v465'){const vid=v();t=Math.max(0,Math.min(vid.duration-.05,t));if(Math.abs(vid.currentTime-t)>.025){if(typeof seek==='function')await seek(t,reason);else await new Promise((res,rej)=>{const done=()=>res();vid.addEventListener('seeked',done,{once:true});vid.currentTime=t;setTimeout(()=>rej(new Error('シーク失敗')),5000)})}await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))}
  function sig(){const src=frameCanvas(300),c=document.createElement('canvas');c.width=40;c.height=18;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data,a=new Uint8Array(c.width*c.height);let j=0;for(let i=0;i<d.length;i+=4)a[j++]=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);return a}
  const diff=(a,b)=>{if(!a||!b)return 0;let s=0;for(let i=0;i<a.length;i++)s+=Math.abs(a[i]-b[i]);return s/(a.length*255)};const med=a=>{if(!a.length)return 0;const b=a.slice().sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};const pct=(a,p)=>{if(!a.length)return 0;const b=a.slice().sort((x,y)=>x-y);return b[Math.min(b.length-1,Math.max(0,Math.floor((b.length-1)*p)))]};const nearest=(rows,t)=>rows.reduce((best,r)=>!best||Math.abs(r.time-t)<Math.abs(best.time-t)?r:best,null);function merge(items,gap=.20){const a=items.slice().sort((x,y)=>x.time-y.time),out=[];for(const it of a){const last=out[out.length-1];if(last&&it.time-last.time<gap){if(it.priority>last.priority)out[out.length-1]=it}else out.push(it)}return out}function timeline(){return Array.isArray(window.turnTimeline39)?window.turnTimeline39.map(x=>({side:x.side,turn:Number(x.turn),time:Number(x.time)})).filter(x=>Number.isFinite(x.time)).sort((a,b)=>a.time-b.time):[]}function scanStep(duration){if(duration>900)return 4;if(duration>600)return 3;if(duration>300)return 2.5;return 2}
  async function selectFrames(start,end,status){const step=scanStep(end-start),rows=[];let prev=null,n=0;for(let t=start;t<=end+.001;t+=step){await seekSafe(t);const s=sig(),d=prev?diff(prev,s):0;rows.push({time:+t.toFixed(3),diff:d});prev=s;n++;if(status)status.textContent=`試合全体を走査中… ${n}`}const ds=rows.slice(1).map(r=>r.diff),m=med(ds),mad=med(ds.map(x=>Math.abs(x-m))),thr=Math.max(.026,m+mad*1.9,pct(ds,.72)*.84),picks=[];const add=(time,priority,reason,d=0)=>{if(Number.isFinite(time)&&time>=start-.05&&time<=end+.05)picks.push({time:+time.toFixed(3),priority,reason,diff:d})};add(start,160,'match-start');add(end,160,'match-end');const mt=Number(window.mulliganPreview442?.time);if(Number.isFinite(mt))add(mt,170,'mulligan');for(const a of timeline().filter(x=>x.time>=start-.1&&x.time<=end+.1)){add(a.time,155,`turn-${a.side}-${a.turn}`);add(a.time-.35,108,'before-turn');add(a.time+.35,108,'after-turn')}const heartbeat=Math.max(5,Math.min(9,(end-start)/32));for(let t=start;t<=end+.001;t+=heartbeat){const r=nearest(rows,t);if(r)add(r.time,48,'continuity',r.diff)}for(let i=1;i<rows.length;i++){const c=rows[i].diff,p=rows[i-1]?.diff??0,nx=rows[i+1]?.diff??0;if(c>=thr&&c>=p&&c>=nx){add(rows[i-1].time,86+c*110,'before-change',c);add(rows[i].time,94+c*125,'change',c)}}for(const r of rows.slice(1).sort((a,b)=>b.diff-a.diff).slice(0,18))add(r.time,82+r.diff*100,'strong-change',r.diff);let selected=merge(picks);const MAX=60;if(selected.length>MAX){const must=selected.filter(x=>x.priority>=150),rest=selected.filter(x=>x.priority<150).sort((a,b)=>b.priority-a.priority||b.diff-a.diff).slice(0,Math.max(0,MAX-must.length));selected=merge([...must,...rest]).sort((a,b)=>a.time-b.time)}return{rows,selected,threshold:+thr.toFixed(4),step}}
  function mount(){if($q('#fullMatchPanel465'))return true;const anchor=$q('#rangeReviewPanel462')||$q('#capture')?.closest('.panel');if(!anchor?.parentNode)return false;const p=document.createElement('section');p.id='fullMatchPanel465';p.className='panel';p.innerHTML=`<h2>試合全体を短評</h2><p class="help">マリガンから試合終了まで重要場面を抽出します。</p><label>見てほしいこと（任意）<textarea id="fullMatchNote465"></textarea></label><div class="buttons"><button id="exportFullMatch465" class="good">試合全体の短評ZIPを作る</button></div><p id="fullMatchStatus465" class="help">動画を読み込んだら実行できます。</p><div id="fullMatchSave465" style="display:none"><div id="fullMatchSaveInfo465" class="help"></div><div class="buttons"><button id="fullMatchSaveBtn465" class="good">ZIPをファイルに保存</button></div></div>`;anchor.parentNode.insertBefore(p,anchor.nextSibling);$q('#exportFullMatch465').onclick=exportFull;$q('#fullMatchSaveBtn465').onclick=savePending;return true}
  async function exportFull(){const vid=v(),status=$q('#fullMatchStatus465'),btn=$q('#exportFullMatch465');if(busy||!vid?.src)return;busy=true;btn.disabled=true;const orig=vid.currentTime;vid.pause();try{const JSZip=await ensureZip(),zip=new JSZip(),mt=Number(window.mulliganPreview442?.time),start=Number.isFinite(mt)?Math.max(.1,mt-.8):.1,end=Math.max(start+.5,vid.duration-.15),sel=await selectFrames(start,end,status),manifest={format:'shadowverse-wb-full-match-review-v4.6.5',build:PATCH,mode:'full-match-short-review',source:typeof videoName!=='undefined'?videoName:'replay',deck:$q('#deck')?.value||'',matchup:$q('#matchup')?.value||'',classDetection:window.classDetection442||null,mulliganPreview:window.mulliganPreview442||null,knownTurnTimeline:timeline(),reviewRequest:{objective:'試合全体を短評し最大の改善点を1つ特定する',note:$q('#fullMatchNote465')?.value||''},fullMatch:{analysisStartTimeSeconds:start,analysisEndTimeSeconds:end,durationSeconds:vid.duration,frames:[]}};let done=0;for(const it of sel.selected){await seekSafe(it.time);const c=frameCanvas(1000),blob=await canvasBlob(c,.62),file=`full-match/frames/frame-${String(++done).padStart(3,'0')}-${it.time.toFixed(2)}s.jpg`;zip.file(file,blob,{compression:'STORE'});manifest.fullMatch.frames.push({file,timeSeconds:it.time,reason:it.reason,diff:+(it.diff||0).toFixed(4)})}zip.file('range-review.json',JSON.stringify(manifest));const blob=await zip.generateAsync({type:'blob',compression:'STORE'}),name=`${safeName(typeof videoName!=='undefined'?videoName:'replay')}-full-match-review-v4.6.5.zip`;pendingFile=new File([blob],name,{type:'application/zip'});$q('#fullMatchSaveInfo465').textContent=`ZIP準備完了：${name}（${size(pendingFile.size)}） / ${done}枚`;$q('#fullMatchSave465').style.display='block';status.textContent='ZIPを作成しました。README等の余計なテキストファイルは出力しません。';safeLog('full-match-ready-v465',{size:pendingFile.size,selectedFrames:done})}catch(e){status.textContent='ZIP作成失敗：'+(e?.message||String(e))}finally{try{await seekSafe(orig)}catch{}busy=false;btn.disabled=false}}
  async function savePending(){const status=$q('#fullMatchStatus465');if(!pendingFile)return;try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[pendingFile]})))await navigator.share({files:[pendingFile]});else status.textContent='この環境では共有シートを利用できません。'}catch(e){if(e?.name!=='AbortError')status.textContent='保存画面を開けませんでした。'}}
  let tries=0;const timer=setInterval(()=>{tries++;if(mount()||tries>100)clearInterval(timer)},150);safeLog('patch-v465-active',{feature:'full-match-short-review-no-readme'});
})();