(()=>{
  const PATCH='4.9.3-20260915-13d',$q=s=>document.querySelector(s),STORE='wb-counterfactual-v1';
  const safeLog=(type,data={})=>{try{log(type,{patch:PATCH,...data})}catch{}};
  const shellFrozen=()=>!!window.__wbLegacyUiFrozen;
  const newerUi=()=>{const v=Number(document.documentElement.dataset.wbLatestUi||0);return v===494||v>=4100};
  if(!shellFrozen()&&!newerUi())document.documentElement.dataset.wbLatestUi='493';
  function readSession(){try{const db=JSON.parse(localStorage.getItem(STORE)||'null'),k=window.__wbCounterfactualV1?.sourceKey;return k?db?.sessions?.[k]:null}catch{return null}}
  function normalizeSide(text,side){const base=String(text||'').split(/\s*\/\s*手番\s*:/)[0].trim();return `${base} / 手番: ${side||'未設定'}`}
  function relabel(){const p=$q('#counterfactualPanel490');if(!p)return false;const labels=[['#cfPp490','手番側PP'],['#cfBar490','自分手札：バルバロス'],['#cfZeta490','自分手札：ゼタ＆ベアトリクス']];for(const [sel,text] of labels){const e=$q(sel),lab=e?.closest('label');if(lab){for(const n of [...lab.childNodes]){if(n.nodeType===Node.TEXT_NODE){n.textContent=text;break}}}}const map=[['#cfExtra490','手番側ExPP使用可'],['#cfEp490','手番側EP使用可'],['#cfSep490','手番側SEP使用可']];for(const [sel,text] of map){const e=$q(sel),lab=e?.closest('label');if(lab){const nodes=[...lab.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE);if(nodes.length)nodes[nodes.length-1].textContent=' '+text}}if(!$q('#cfSemantics493')){const x=document.createElement('p');x.id='cfSemantics493';x.className='help';x.textContent='PP・ExPP・EP・SEPは「次に動く側」の資源です。バルバロス／ゼタベア欄は自分の既知手札です。相手手番の枝はリーサル検証へ直接送らず、自分手番の子枝を作ってから送ります。';p.querySelector('p.help')?.insertAdjacentElement('afterend',x)}if(window.__wbCounterfactualV1?.protocol)window.__wbCounterfactualV1.protocol.resourceSemantics='pp/extraPPAvailable/epAvailable/sepAvailable are resources of state.sideToAct; hand fields describe the reviewed player own known hand.';return true}
  function markLegacy(){const s=readSession(),bs=s?.branches||[],list=$q('#cfList490'),p=$q('#counterfactualPanel490');if(!list||!p)return false;const missing=bs.filter(b=>!b.state?.sideToAct);let note=$q('#cfLegacy493');if(missing.length){if(!note){note=document.createElement('p');note.id='cfLegacy493';note.className='help';note.style.color='#fbbf24';p.querySelector('#cfList490')?.insertAdjacentElement('beforebegin',note)}note.textContent=`旧形式の分岐 ${missing.length}件は「手番」が未設定です。編集して「次に動く側」を選び直してください。`;for(const b of missing){const btn=list.querySelector(`[data-edit-cf="${b.id}"]`),card=btn?.closest('div[style*="border"]'),help=card?Array.from(card.children).find(x=>x.classList?.contains('help')):null;if(help)help.textContent=normalizeSide(help.textContent,'未設定')}}else if(note)note.remove();return true}
  function updater(){if(shellFrozen()||newerUi())return true;const old=$q('#wbForceLatest463')||$q('#wbForceLatest462');if(!old)return false;if(old.dataset.wb493==='1')return true;const b=old.cloneNode(true);b.dataset.wb493='1';b.dataset.wb492='1';old.replaceWith(b);const st=$q('#wbUpdateStatus463')||$q('#wbUpdateStatus462');if(st)st.textContent='v4.9.3 / 分岐資源・表示修正版';b.addEventListener('click',async()=>{if(shellFrozen()||newerUi())return;if(b.disabled)return;b.disabled=true;if(st)st.textContent='最新版を確認中…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js?v=4.9.3-20260915-13d',{updateViaCache:'none'});await reg.update()}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('wb-review-')&&k!=='wb-review-v4-9-3-20260915-13d').map(k=>caches.delete(k)))}if(st)st.textContent='更新完了。v4.9.3で再起動します…';setTimeout(()=>{const u=new URL(location.href);u.searchParams.set('latest','493d-'+Date.now());u.hash='';location.replace(u.href)},180)}catch(err){if(st)st.textContent='更新確認に失敗しました。';b.disabled=false;safeLog('force-latest-error-v493',{message:err?.message||String(err)})}});return true}
  if(!document.documentElement.dataset.wb493Events){document.documentElement.dataset.wb493Events='1';document.addEventListener('click',e=>{const send=e.target?.closest?.('[data-send-cf]');if(!send)return;const b=readSession()?.branches?.find(x=>x.id===send.dataset.sendCf);if(b&&!b.state?.sideToAct){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();const st=$q('#cfStatus490');if(st){st.textContent='この旧分岐は手番が未設定です。「編集」で次に動く側を設定してからリーサル検証へ送ってください。';st.style.color='#fca5a5'}}},true)}
  let n=0;const tm=setInterval(()=>{n++;relabel();markLegacy();if(!shellFrozen()&&!newerUi()){document.documentElement.dataset.wbLatestUi='493';updater();const h=$q('header h1'),s=$q('header p');if(h)h.textContent='シャドバWB リプレイ診断 v4.9.3';if(s)s.textContent='Build 2026.09.15-13d / 分岐資源・旧枝手番・最新版表示を修正'}if(n>600)clearInterval(tm)},120);
  safeLog('patch-v493-active',{feature:'branch-resource-semantics-latest-ui-and-legacy-side-guard',legacyUiSuppressed:shellFrozen()});
})();