(function(){
'use strict';
const root=typeof window==='undefined'?globalThis:window,WB=root.WB=root.WB||{},VERSION='pc1-outcome-search-v1.0.0';
function create(deps={},options={}){const L=deps.legalEngine,C=deps.core;if(!L||!C)throw new Error('P-C1 search requires P-A1 legalEngine and OutcomeCore instance');const R=WB.OutcomeCore.REASON,S=WB.OutcomeCore.STATUS,cfg={maxDepth:10,maxNodes:1200,maxBranches:24,maxOpponentResponses:16,maxContinuations:24,maxTurns:3,...options};
 function analyze(start,perspective,limits={}){const lim={maxDepth:limits.maxDepth??cfg.maxDepth,maxNodes:limits.maxNodes??cfg.maxNodes,maxBranches:limits.maxBranches??cfg.maxBranches,maxOpponentResponses:limits.maxOpponentResponses??cfg.maxOpponentResponses,maxContinuations:limits.maxContinuations??cfg.maxContinuations,maxTurns:limits.maxTurns??cfg.maxTurns},graph=[],memo=new Map();let nodes=0,memoHits=0,duplicates=0,cycles=0;const limitsHit=[];
  function leaf(s,ctx,reason,unknown=false){const z=C.snapshot(s,perspective),od=z&&z.opponentLeaderHP!=null&&z.opponentLeaderHP<=0,sd=z&&z.leaderHP!=null&&z.leaderHP<=0;return {lethalPossible:!!od,lethalForced:!!od,earliestOwnTurn:od?ctx.ownTurnsAfterStart:null,survivalPossible:!sd,survivalForced:!sd,deathForced:!!sd,unknownLethal:unknown||!z,unknownSurvival:unknown||!z,unknown:unknown||!z,reasonCodes:C.uniq([reason])};}
  function unknownCodes(g,h){const rs=[];if(h.status!=='KNOWN')rs.push(R.OPPONENT_RESPONSE_UNKNOWN_HAND,...h.reasonCodes);for(const x of g&&g.unknown||[])rs.push(...(x.reasonCodes||[R.UNRESOLVED_OUTCOME]));if(g&&g.status==='UNRESOLVED')rs.push(...(g.reasonCodes||[R.UNRESOLVED_OUTCOME]));return C.uniq(rs);}
  function solve(s,ctx,path){const f=C.fp(s),active=C.A.getActivePlayer(s),key=`${f}|${active}|${ctx.depth}|${ctx.turnTransitions}|${ctx.ownTurnsAfterStart}|${ctx.opponentTurnsAfterStart}`;if(path.has(f)){cycles++;return leaf(s,ctx,R.CYCLE_DETECTED,true);}if(memo.has(key)){memoHits++;duplicates++;return memo.get(key);}if(nodes>=lim.maxNodes){limitsHit.push(R.NODE_LIMIT);return leaf(s,ctx,R.NODE_LIMIT,true);}if(ctx.depth>=lim.maxDepth){limitsHit.push(R.DEPTH_LIMIT);return leaf(s,ctx,R.DEPTH_LIMIT,true);}if(ctx.turnTransitions>=lim.maxTurns){limitsHit.push(R.TURN_LIMIT);return leaf(s,ctx,R.TURN_LIMIT,true);}const t=C.terminal(s);if(t.unresolved)return leaf(s,ctx,t.reasons&&t.reasons.includes(R.INDETERMINATE_RULE_ORDER)?R.INDETERMINATE_RULE_ORDER:R.UNRESOLVED_OUTCOME,true);if(t.terminal)return leaf(s,ctx,R.TERMINAL_PRUNED,false);
   const g=L.generateLegalActions(s,{sequenceDepth:ctx.depth}),isOpponent=active!==perspective,h=isOpponent?C.hidden(s,active):{status:'KNOWN',reasonCodes:[]},u=unknownCodes(g,h);if(!g||g.status!=='OK'){const v=leaf(s,ctx,(g&&g.reasonCodes&&g.reasonCodes[0])||R.UNRESOLVED_OUTCOME,true);v.reasonCodes=C.uniq([...v.reasonCodes,...u]);return v;}
   let actions=(g.actions||[]).slice(),cap=isOpponent?lim.maxOpponentResponses:lim.maxContinuations;if(actions.length>lim.maxBranches){actions=actions.slice(0,lim.maxBranches);limitsHit.push(R.BRANCH_LIMIT);}if(actions.length>cap){actions=actions.slice(0,cap);limitsHit.push(isOpponent?R.OPPONENT_RESPONSE_LIMIT:R.CONTINUATION_LIMIT);}const entry={nodeId:`N${graph.length+1}`,stateId:C.sid(s),stateFingerprint:f,activePlayer:active,role:isOpponent?'OPPONENT_RESPONSE':'SELF_CONTINUATION',depth:ctx.depth,turnTransitions:ctx.turnTransitions,ownTurnsAfterStart:ctx.ownTurnsAfterStart,opponentTurnsAfterStart:ctx.opponentTurnsAfterStart,unknownDependencies:u,responseClass:isOpponent?(actions.length?null:WB.OutcomeCore.RESPONSE_CLASS.NO_KNOWN_RESPONSE):null,children:[]};graph.push(entry);nodes++;
   if(!actions.length){const v=leaf(s,ctx,R.NO_KNOWN_OPPONENT_RESPONSE,u.length>0);if(isOpponent)v.reasonCodes=C.uniq([...v.reasonCodes,R.NO_KNOWN_OPPONENT_RESPONSE,...u]);memo.set(key,v);return v;}
   const vals=[],nextPath=new Set(path);nextPath.add(f);for(const action of actions){const ap=L.applyAction(s,action),child={actionId:action.actionId,actionType:action.actionType,responseClass:isOpponent?C.responseClass(action):null,status:ap&&ap.status||S.ERROR,reasonCodes:C.uniq(ap&&ap.reasonCodes)};entry.children.push(child);if(!ap||!ap.state||['UNRESOLVED','INVALID','ERROR'].includes(ap.status)){vals.push({lethalPossible:false,lethalForced:false,earliestOwnTurn:null,survivalPossible:true,survivalForced:false,deathForced:false,unknownLethal:true,unknownSurvival:true,unknown:true,reasonCodes:C.uniq([...(ap&&ap.reasonCodes||[]),R.UNRESOLVED_OUTCOME])});continue;}const na=C.A.getActivePlayer(ap.state),changed=na!==active,tt=ctx.turnTransitions+(changed?1:0),ot=ctx.ownTurnsAfterStart+(changed&&na===perspective?1:0),pt=ctx.opponentTurnsAfterStart+(changed&&na!==perspective?1:0);let val=solve(ap.state,{depth:ctx.depth+1,turnTransitions:tt,ownTurnsAfterStart:ot,opponentTurnsAfterStart:pt},nextPath);const em=C.eventMetrics(C.events(s,ap.state,{perspective,action}),perspective,C.opponent(ap.state,perspective));if(em.unknownDraw)val={...val,unknownLethal:true,unknownSurvival:true,unknown:true,reasonCodes:C.uniq([...(val.reasonCodes||[]),R.UNKNOWN_DRAW,R.LETHAL_DEPENDS_ON_UNKNOWN_DRAW])};vals.push(val);child.resultStateId=C.sid(ap.state);child.resultStateFingerprint=C.fp(ap.state);}
   const anyL=vals.some(x=>x.lethalPossible),earliest=vals.filter(x=>x.earliestOwnTurn!=null).reduce((m,x)=>m==null?x.earliestOwnTurn:Math.min(m,x.earliestOwnTurn),null),lf=isOpponent?u.length===0&&vals.length>0&&vals.every(x=>x.lethalForced&&!x.unknownLethal):vals.some(x=>x.lethalForced&&!x.unknownLethal),sp=isOpponent?vals.every(x=>x.survivalPossible):vals.some(x=>x.survivalPossible),sf=isOpponent?u.length===0&&vals.every(x=>x.survivalForced&&!x.unknownSurvival):vals.some(x=>x.survivalForced&&!x.unknownSurvival),df=isOpponent?vals.some(x=>x.deathForced&&!x.unknownSurvival):vals.length>0&&vals.every(x=>x.deathForced&&!x.unknownSurvival),ul=isOpponent?(u.length>0||vals.some(x=>x.unknownLethal)):(!lf&&vals.some(x=>x.unknownLethal)),us=isOpponent?(df?false:(u.length>0||vals.some(x=>x.unknownSurvival))):(sf||df?false:vals.some(x=>x.unknownSurvival)),reasons=C.uniq([...u,...vals.flatMap(x=>x.reasonCodes||[])]),v={lethalPossible:anyL,lethalForced:lf,earliestOwnTurn:earliest,survivalPossible:sp,survivalForced:sf,deathForced:df,unknownLethal:ul,unknownSurvival:us,unknown:ul||us,reasonCodes:reasons};memo.set(key,v);return v;}
  const verdict=solve(start,{depth:0,turnTransitions:0,ownTurnsAfterStart:0,opponentTurnsAfterStart:0},new Set());return {verdict,graph,diagnostics:{nodes,memoHits,duplicates,cycles,limits:lim,limitsHit:C.uniq(limitsHit)},memoization:{entries:memo.size,hits:memoHits,keyAuthority:'P-A1 stateFingerprint + search context'}};}
 function future(start,perspective,limits={}){const x=analyze(start,perspective,limits),v=x.verdict,rs=[...v.reasonCodes];if(v.lethalForced&&v.earliestOwnTurn===1&&!v.unknownLethal)rs.push(R.NEXT_TURN_LETHAL_CONFIRMED);else if(v.lethalPossible&&v.earliestOwnTurn===1)rs.push(R.NEXT_TURN_LETHAL_POSSIBLE);else if(v.lethalPossible)rs.push(R.MULTI_TURN_LETHAL_POSSIBLE);if(v.survivalForced&&!v.unknownSurvival)rs.push(R.SURVIVAL_CONFIRMED);else if(v.deathForced&&!v.unknownSurvival)rs.push(R.CONFIRMED_DEATH);else if(!v.survivalForced)rs.push(R.SURVIVAL_NOT_GUARANTEED);return {status:x.diagnostics.limitsHit.length?S.LIMIT:S.OK,verdict:C.clone(v),bestConfirmedOutcome:{lethalPossible:v.lethalPossible,earliestOwnTurn:v.earliestOwnTurn,survivalPossible:v.survivalPossible},worstConfirmedOutcome:{lethalForced:v.lethalForced,survivalForced:v.survivalForced,deathForced:v.deathForced},unknownDependentOutcome:(v.unknownLethal||v.unknownSurvival)?{present:true,reasonCodes:C.uniq(v.reasonCodes.filter(r=>String(r).includes('UNKNOWN')||String(r).includes('UNRESOLVED')||String(r).includes('INDETERMINATE')))}:{present:false,reasonCodes:[]},opponentResponses:x.graph.filter(n=>n.role==='OPPONENT_RESPONSE').map(n=>({stateId:n.stateId,unknownDependencies:n.unknownDependencies,responseClasses:n.children.map(c=>c.responseClass).filter(Boolean),knownResponseCount:n.children.length})),continuations:x.graph.filter(n=>n.role==='SELF_CONTINUATION').map(n=>({stateId:n.stateId,continuationCount:n.children.length})),reasonCodes:C.uniq(rs),evidence:{graph:x.graph},diagnostics:x.diagnostics,memoization:x.memoization};}
 return Object.freeze({version:VERSION,analyzeFuture:analyze,futureOutcome:future});}
WB.OutcomeSearch=Object.freeze({version:VERSION,create});if(typeof WB.registerModule==='function')WB.registerModule('outcome-search',VERSION);
})();