(()=>{'use strict';
const W=window.WB;if(!W)return;
const V='review-clean-1.2',LS='wb-lethal-v2',CS='wb-counterfactual-v1';W.registerModule('review-engine',V);
const rules={protocol:{beforeGrade:['主要リーサル候補を全列挙する','相手HP・PP・Extra PP・EP・SEP・守護・場の打点・海賊旗カウント・主要手札を確認する','不明情報が残る場合はリーサルなしと断定しない','反実仮想は分岐直前から独立再計算する']},independentState:true,branchAssist:'branch-assist-clean'};
const clone=x=>JSON.parse(JSON.stringify(x)),key=()=>W.videoMeta?`${W.videoMeta.name}|${W.videoMeta.size}|${W.videoMeta.lastModified}`:null,load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},save=(k,x)=>{try{localStorage.setItem(k,JSON.stringify(x))}catch(e){W.recordError('review-persist',e)}};
let ld=load(LS,{sessions:{}}),cd=load(CS,{sessions:{}}),cfDraft=null;
const ses=(db,make=true)=>{const k=key();if(!k)return null;db.sessions??={};if(make&&!db.sessions[k])db.sessions[k]={sourceKey:k,snapshots:[],branches:[]};return db.sessions[k]};
const val=id=>W.$(id)?.value??'',num=(id,d=null)=>{const raw=val(id);if(raw==='')return d;const x=Number(raw);return Number.isFinite(x)?x:d},bool=v=>v==='yes'?true:v==='no'?false:null;
const parseFlags=raw=>{raw=String(raw??'').trim();if(!raw)return{known:false,values:[]};const values=raw.split(/[、,\s]+/).map(Number).filter(Number.isFinite);return{known:true,values}};
function state(){const c=W.currentTurnContext(),fg=parseFlags(val('#leFlags')),boardRaw=String(val('#leBoard')).trim(),otherRaw=String(val('#leOther')).trim();return{turn:num('#leTurn',c.turn),opponentHP:num('#leOppHp'),pp:num('#lePp'),extraPP:val('#leExtra')||'unknown',ep:val('#leEp')||'unknown',sep:val('#leSep')||'unknown',opponentWard:val('#leWard')||'unknown',pirateFlagCountdowns:fg.values,pirateFlagsKnown:fg.known,knownBoardLeaderDamage:boardRaw===''?null:Math.max(0,Number(boardRaw)||0),boardDamageKnown:boardRaw!=='',otherConfirmedLeaderDamage:otherRaw===''?null:Math.max(0,Number(otherRaw)||0),otherDamageKnown:otherRaw!=='',hand:{barbaros:val('#leBar')||'unknown',zetaBeatrix:val('#leZeta')||'unknown',otherDamageRoutesChecked:val('#leOthersChecked')==='yes'},sideToAct:'自分',observedAtSeconds:Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null}}
function calculate(s=state()){const hp=Number.isFinite(Number(s.opponentHP))?Number(s.opponentHP):null,pp=Number.isFinite(Number(s.pp))?Number(s.pp):null,ex=s.extraPP??(s.extraPPAvailable==null?'unknown':s.extraPPAvailable?'yes':'no'),ep=s.ep??(s.epAvailable==null?'unknown':s.epAvailable?'yes':'no'),sep=s.sep??(s.sepAvailable==null?'unknown':s.sepAvailable?'yes':'no'),ward=typeof s.opponentWard==='string'?s.opponentWard:s.opponentWard===true?'present':s.opponentWard===false?'none':'unknown',bar=s.hand?.barbaros||'unknown',z=s.hand?.zetaBeatrix||'unknown',otherOk=!!s.hand?.otherDamageRoutesChecked,flagsKnown=s.pirateFlagsKnown!==false&&Array.isArray(s.pirateFlagCountdowns),boardKnown=s.boardDamageKnown!==false&&Number.isFinite(Number(s.knownBoardLeaderDamage)),otherKnown=s.otherDamageKnown!==false&&Number.isFinite(Number(s.otherConfirmedLeaderDamage)),eff=pp==null?null:pp+(bool(ex)===true?1:0),fixed=(boardKnown?Math.max(0,+s.knownBoardLeaderDamage||0):0)+(otherKnown?Math.max(0,+s.otherConfirmedLeaderDamage||0):0),fs=flagsKnown?s.pirateFlagCountdowns.map(Number).filter(Number.isFinite):[],unknown=[],routes=[];
if(hp==null)unknown.push('相手HP');if(pp==null)unknown.push('PP');if(ex==='unknown')unknown.push('Extra PP');if(ep==='unknown')unknown.push('EP');if(sep==='unknown')unknown.push('SEP');if(ward==='unknown')unknown.push('守護');if(!boardKnown)unknown.push('場の打点');if(!otherKnown)unknown.push('その他確定打点');if(!flagsKnown)unknown.push('海賊旗カウント');if(bar==='unknown')unknown.push('バルバロス所持');if(z==='unknown')unknown.push('ゼタ＆ベアトリクス所持');if(!otherOk)unknown.push('その他の手札打点');
const add=(name,cost,damage)=>routes.push({name,cost,damage,wardState:ward,lethal:hp!=null&&damage>=hp&&ward==='none'});if(hp!=null&&boardKnown&&fixed>=hp)add('場＋その他確定打点',0,fixed);if(bar==='have'&&eff!=null&&eff>=7&&flagsKnown&&boardKnown){const d=4+fs.filter(x=>x<=5).length*2+fixed;add('バルバロス',7,d);if(bool(ep))add('バルバロス＋進化',7,d+2);if(bool(sep))add('バルバロス＋超進化',7,d+3)}if(z==='have'&&eff!=null&&eff>=6&&boardKnown){const d=3+fixed;add('ゼタ＆ベアトリクス（エンハンス6）',6,d);if(bool(ep))add('ゼタ＆ベアトリクス＋進化',6,d+2);if(bool(sep))add('ゼタ＆ベアトリクス＋超進化',6,d+3)}const lethalRoutes=routes.filter(x=>x.lethal).map(x=>x.name),status=lethalRoutes.length?'confirmed-lethal':unknown.length?'incomplete-do-not-declare-no-lethal':'checked-no-lethal-in-covered-routes';return{...clone(s),effectivePP:eff,routes,lethalRoutes,unknown,status}}
function renderLethal(){const o=W.$('#leResult');if(!o)return null;const x=calculate();o.textContent=`${x.turn??'?'}T / 有効PP ${x.effectivePP??'?'} / 相手HP ${x.opponentHP??'?'}\n`+(x.routes.map(r=>`${r.lethal?'◎ ':''}${r.name}：${r.damage}点${r.wardState==='present'?'（守護あり）':r.wardState==='unknown'?'（守護未確認）':''}`).join('\n')||'該当する既知ルートはまだ計算できません。')+(x.lethalRoutes.length?`\nリーサル候補：${x.lethalRoutes.join(' / ')}`:x.unknown.length?`\n未確認：${x.unknown.join(' / ')}\n→「リーサルなし」と断定禁止`:'\n確認対象ルート内ではリーサルなし');return x}
function expose(){const l=ses(ld,false),c=ses(cd,false);window.__wbLethalV2={sourceKey:key(),snapshots:clone(l?.snapshots||[]),protocol:rules.protocol};window.__wbCounterfactualV1={sourceKey:key(),branches:clone(c?.branches||[]),protocol:{independentState:true}}}
function saveL(){const s=state(),critical=['extraPP','ep','sep','opponentWard'].filter(k=>s[k]==='unknown');if(critical.length){W.$('#leStatus').textContent=`保存しません：${critical.join(' / ')} が未確認です。`;return}const x=calculate(s),q=ses(ld);x.id='l'+Date.now().toString(36);x.createdAt=new Date().toISOString();q.snapshots.push(x);save(LS,ld);expose();W.$('#leStatus').textContent=`${x.turn??'?'}Tの状態を保存しました。`;renderSaved()}
function renderSaved(){const o=W.$('#leSaved'),q=ses(ld,false)?.snapshots||[];if(o)o.innerHTML=q.slice(-6).map(x=>`<div class="branchItem"><b>${x.turn??'?'}T</b><div>${x.lethalRoutes?.length?'候補：'+W.escape(x.lethalRoutes.join(' / ')):x.unknown?.length?'未確認：'+W.escape(x.unknown.join(' / ')):'主要候補内リーサルなし'}</div></div>`).join('')}
function cf(){return ses(cd)}
function branchEval(b){return b?.evaluation||b?.automation?.lethalResult||null}
function renderCf(){const o=W.$('#cfList'),q=cf()?.branches||[],p=W.$('#cfParent');if(p){const old=p.value;p.innerHTML='<option value="">親なし（起点）</option>'+q.map(b=>`<option value="${b.id}">${W.escape(b.name)} / ${b.state?.turn??'?'}T</option>`).join('');if(q.some(b=>b.id===old))p.value=old}if(o)o.innerHTML=q.map(b=>{const e=branchEval(b),txt=e?.lethalRoutes?.length?'リーサル候補 '+e.lethalRoutes.join(' / '):e?.status==='incomplete-do-not-declare-no-lethal'?'未確認あり':e?.status==='checked-no-lethal-in-covered-routes'?'主要既知ルート内リーサルなし':'';return`<div class="branchItem"><b>${W.escape(b.name)}</b><div>${b.state?.turn??'?'}T / 手番 ${W.escape(b.state?.sideToAct||'未設定')} / 判断時点 ${b.knowledgeCutoffSeconds??'?'}s${txt?`<br>${W.escape(txt)}`:''}</div></div>`}).join('');refreshAssist()}
function loadCurrentCf(){cfDraft={state:clone(state()),knowledgeCutoffSeconds:Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null};const st=W.$('#cfStatus');if(st)st.textContent=`現在のリーサル状態を分岐下書きへ取り込みました（${cfDraft.state.turn??'?'}T）。`;W.log('counterfactual-load-current',{turn:cfDraft.state.turn,cutoff:cfDraft.knowledgeCutoffSeconds})}
function newCf(){cfDraft=null;for(const id of ['#cfName','#cfNote']){const e=W.$(id);if(e)e.value=''}const p=W.$('#cfParent');if(p)p.value='';const side=W.$('#cfSide');if(side)side.value='自分';const kind=W.$('#cfKind');if(kind)kind.value='counterfactual';const st=W.$('#cfStatus');if(st)st.textContent='新しい分岐を入力できます。'}
function saveCf(){const q=cf(),name=String(val('#cfName')).trim();if(!q||!name){const st=W.$('#cfStatus');if(st)st.textContent='分岐名を入力してください。';return}const parentId=val('#cfParent')||null,parent=q.branches.find(b=>b.id===parentId);let s,cut;if(parent){s=clone(parent.state);cut=parent.knowledgeCutoffSeconds}else if(cfDraft){s=clone(cfDraft.state);cut=cfDraft.knowledgeCutoffSeconds}else{s=state();cut=Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null}if(cut==null)return;s.sideToAct=val('#cfSide')||'自分';const ev=calculate(s),b={id:'b'+Date.now().toString(36),name,kind:val('#cfKind')||'counterfactual',parentId,state:s,evaluation:{status:ev.status,lethalRoutes:ev.lethalRoutes,unknown:ev.unknown},knowledgeCutoffSeconds:cut,note:String(val('#cfNote')).trim(),origin:'clean-v4.11.0'};q.branches.push(b);save(CS,cd);cfDraft=null;expose();renderCf();W.$('#cfStatus').textContent=`「${name}」を独立状態として保存しました。`}
function sameTurnTemplate(src){const snaps=ses(ld,false)?.snapshots||[];return snaps.filter(x=>+x.turn===+src?.state?.turn&&Number.isFinite(+x.pp)).slice(-1)[0]||null}
function renderAssistTemplate(){const q=cf(),src=q?.branches.find(b=>b.id===val('#asSource')),o=W.$('#asTemplate');if(!o)return;if(!src){o.textContent='相手手番の起点を選択してください。';return}const tpl=sameTurnTemplate(src);o.textContent=tpl?`資源テンプレート：${src.state?.turn??'?'}T / PP ${tpl.pp} / ExPP ${tpl.extraPP??'unknown'} / EP ${tpl.ep??'unknown'} / SEP ${tpl.sep??'unknown'}`:'同ターンの保存済みリーサル状態がないため、PP/ExPP/EP/SEPは推測しません。'}
function renderAssistResults(){const o=W.$('#asResults'),q=cf()?.branches.filter(b=>b.origin==='branch-assist-clean')||[];if(!o)return;o.innerHTML=q.slice(-6).reverse().map(b=>{const r=b.automation?.lethalResult||{};const txt=r.lethalRoutes?.length?'候補：'+r.lethalRoutes.join(' / '):r.status==='incomplete-do-not-declare-no-lethal'?'未確認：'+(r.unknown||[]).join(' / '):'主要既知ルート内ではリーサルなし';return`<div class="branchItem"><b>${W.escape(b.name)}</b><div>${W.escape(txt)}</div></div>`}).join('')}
function refreshAssist(){const s=W.$('#asSource'),q=cf()?.branches.filter(b=>b.state?.sideToAct==='相手')||[];if(!s)return;const old=s.value;s.innerHTML=q.map(b=>`<option value="${b.id}">${W.escape(b.name)} / ${b.state?.turn??'?'}T</option>`).join('')||'<option value="">相手手番の起点がありません</option>';if(q.some(b=>b.id===old))s.value=old;renderAssistTemplate();renderAssistResults()}
function assist(){const q=cf(),src=q?.branches.find(b=>b.id===val('#asSource')),name=String(val('#asName')).trim();if(!src||!name){const st=W.$('#asStatus');if(st)st.textContent='相手手番の起点と返し名を指定してください。';return}const tpl=sameTurnTemplate(src),s=clone(src.state),fg=parseFlags(val('#asFlags')),boardRaw=String(val('#asBoard')).trim(),otherRaw=String(val('#asOther')).trim();s.sideToAct='自分';s.opponentHP=num('#asOppHp');s.selfHP=num('#asSelfHp');s.opponentWard=val('#asWard')||'unknown';s.pirateFlagCountdowns=fg.values;s.pirateFlagsKnown=fg.known;s.knownBoardLeaderDamage=boardRaw===''?null:Math.max(0,Number(boardRaw)||0);s.boardDamageKnown=boardRaw!=='';s.otherConfirmedLeaderDamage=otherRaw===''?null:Math.max(0,Number(otherRaw)||0);s.otherDamageKnown=otherRaw!=='';if(tpl){for(const k of ['pp','extraPP','ep','sep'])s[k]=tpl[k]??s[k]}else{s.pp=null;s.extraPP=s.ep=s.sep='unknown'}const r=calculate(s),b={id:'a'+Date.now().toString(36),name,kind:'counterfactual',parentId:src.id,state:s,knowledgeCutoffSeconds:src.knowledgeCutoffSeconds,note:String(val('#asNote')).trim(),origin:'branch-assist-clean',automation:{resourceStatus:tpl?'from-saved-lethal-snapshot':'missing-template',lethalResult:{status:r.status,lethalRoutes:r.lethalRoutes,unknown:r.unknown}}};q.branches.push(b);save(CS,cd);expose();renderCf();W.$('#asStatus').textContent=r.lethalRoutes.length?`「${name}」：リーサル候補 ${r.lethalRoutes.join(' / ')}`:r.status==='incomplete-do-not-declare-no-lethal'?`「${name}」：未確認情報あり。リーサルなしとは断定しません。`:`「${name}」：主要既知ルート内ではリーサルなし`}
W.ReviewEngine={version:V,rules,calculate,state,renderLethal,expose};
W.onReady(()=>{W.$('#leCalc')?.addEventListener('click',renderLethal);W.$('#leSave')?.addEventListener('click',saveL);W.$('#cfLoadState')?.addEventListener('click',loadCurrentCf);W.$('#cfSave')?.addEventListener('click',saveCf);W.$('#cfNew')?.addEventListener('click',newCf);W.$('#asSource')?.addEventListener('change',renderAssistTemplate);W.$('#asCreate')?.addEventListener('click',assist);W.on('video-reset',()=>{cfDraft=null;expose();renderSaved();renderCf()});expose();renderLethal();renderSaved();renderCf();W.log('module-ready',{module:'review-engine',version:V,counterfactualUiComplete:true,branchAssistResults:true})})})();
