(()=>{'use strict';
const W=window.WB;if(!W)return;
const V='review-clean-1.3',LS='wb-lethal-v2',CS='wb-counterfactual-v1';W.registerModule('review-engine',V);
const rules={protocol:{beforeGrade:['主要リーサル候補を全列挙する','相手HP・PP・Extra PP・EP・SEP・守護・場の攻撃可能総打点・戦術情報を確認する','不明情報が残る場合はリーサルなしと断定しない','反実仮想は分岐直前から独立再計算する']},independentState:true,branchAssist:'branch-assist-clean',tacticalSummary:'dynamic-catalog-v1'};
const TACTICAL_CARDS=Object.freeze([
  {id:'barbaros',label:'バルバロス',category:'フィニッシャー',maxCount:3},
  {id:'zetaBeatrix',label:'ゼタ＆ベアトリクス',category:'疾走・フィニッシャー',maxCount:3},
  {id:'quickBlader',label:'刹那のクイックブレイダー',category:'疾走',maxCount:3,cost:1,baseDamage:1,evolveBonus:2,superBonus:3}
]);
const TACTICAL_RESOURCES=Object.freeze([
  {id:'pirateFlags',label:'海賊旗カウント',kind:'text',placeholder:'例 5,2'},
  {id:'otherConfirmedDamage',label:'その他確定打点',kind:'number',placeholder:'0なら0を入力'},
  {id:'damageRoutesChecked',label:'即時打点候補の確認',kind:'coverage'}
]);
const clone=x=>JSON.parse(JSON.stringify(x)),key=()=>W.videoMeta?`${W.videoMeta.name}|${W.videoMeta.size}|${W.videoMeta.lastModified}`:null,load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},save=(k,x)=>{try{localStorage.setItem(k,JSON.stringify(x))}catch(e){W.recordError('review-persist',e)}};
let ld=load(LS,{sessions:{}}),cd=load(CS,{sessions:{}}),cfDraft=null;
const ses=(db,make=true)=>{const k=key();if(!k)return null;db.sessions??={};if(make&&!db.sessions[k])db.sessions[k]={sourceKey:k,snapshots:[],branches:[]};return db.sessions[k]};
const val=id=>W.$(id)?.value??'',num=(id,d=null)=>{const raw=val(id);if(raw==='')return d;const x=Number(raw);return Number.isFinite(x)?x:d},bool=v=>v==='yes'?true:v==='no'?false:null;
const parseFlags=raw=>{raw=String(raw??'').trim();if(!raw)return{known:false,values:[]};const values=raw.split(/[、,\s]+/).map(Number).filter(Number.isFinite);return{known:true,values}};
const tacticalCardEl=id=>W.$(`[data-tactical-card="${id}"]`),tacticalResourceEl=id=>W.$(`[data-tactical-resource="${id}"]`);
function readTactical(){
  const cards={};
  for(const card of TACTICAL_CARDS){const raw=String(tacticalCardEl(card.id)?.value??'unknown'),n=Number(raw);cards[card.id]=raw==='unknown'||!Number.isInteger(n)?{id:card.id,label:card.label,category:card.category,known:false,count:null}:{id:card.id,label:card.label,category:card.category,known:true,count:Math.max(0,Math.min(card.maxCount,n))}}
  const fg=parseFlags(tacticalResourceEl('pirateFlags')?.value??''),otherRaw=String(tacticalResourceEl('otherConfirmedDamage')?.value??'').trim(),otherNum=Number(otherRaw),coverage=String(tacticalResourceEl('damageRoutesChecked')?.value??'unknown');
  return{version:'tactical-v1',cards,resources:{pirateFlags:{known:fg.known,values:fg.values},otherConfirmedDamage:{known:otherRaw!==''&&Number.isFinite(otherNum),value:otherRaw!==''&&Number.isFinite(otherNum)?Math.max(0,otherNum):null},damageRoutesChecked:coverage==='yes'},observedAtSeconds:Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null}
}
const legacyStatus=c=>!c?.known?'unknown':Number(c.count)>0?'have':'none';
function normalizeCard(s,id,legacyKey){
  const c=s?.tactical?.cards?.[id]||s?.hand?.cards?.[id];
  if(c&&typeof c==='object'&&('known'in c||'count'in c)){const count=Number(c.count);return{id,label:TACTICAL_CARDS.find(x=>x.id===id)?.label||id,known:c.known!==false&&Number.isFinite(count),count:c.known===false||!Number.isFinite(count)?null:Math.max(0,count)}}
  const legacy=s?.hand?.[legacyKey];return{id,label:TACTICAL_CARDS.find(x=>x.id===id)?.label||id,known:legacy==='have'||legacy==='none',count:legacy==='have'?1:legacy==='none'?0:null}
}
function normalizeTactical(s){
  const cards={barbaros:normalizeCard(s,'barbaros','barbaros'),zetaBeatrix:normalizeCard(s,'zetaBeatrix','zetaBeatrix'),quickBlader:normalizeCard(s,'quickBlader','quickBlader')};
  const tr=s?.tactical?.resources||{},flags=tr.pirateFlags&&typeof tr.pirateFlags==='object'?{known:tr.pirateFlags.known!==false,values:Array.isArray(tr.pirateFlags.values)?tr.pirateFlags.values.map(Number).filter(Number.isFinite):[]}:{known:s?.pirateFlagsKnown!==false&&Array.isArray(s?.pirateFlagCountdowns),values:Array.isArray(s?.pirateFlagCountdowns)?s.pirateFlagCountdowns.map(Number).filter(Number.isFinite):[]};
  const od=tr.otherConfirmedDamage&&typeof tr.otherConfirmedDamage==='object'?{known:tr.otherConfirmedDamage.known!==false&&Number.isFinite(Number(tr.otherConfirmedDamage.value)),value:Number.isFinite(Number(tr.otherConfirmedDamage.value))?Math.max(0,Number(tr.otherConfirmedDamage.value)):null}:{known:s?.otherDamageKnown!==false&&Number.isFinite(Number(s?.otherConfirmedLeaderDamage)),value:Number.isFinite(Number(s?.otherConfirmedLeaderDamage))?Math.max(0,Number(s.otherConfirmedLeaderDamage)):null};
  const checked=typeof tr.damageRoutesChecked==='boolean'?tr.damageRoutesChecked:!!s?.hand?.otherDamageRoutesChecked;
  return{version:'tactical-v1',cards,resources:{pirateFlags:flags,otherConfirmedDamage:od,damageRoutesChecked:checked}}
}
function state(){const c=W.currentTurnContext(),t=readTactical(),boardRaw=String(val('#leBoard')).trim();return{turn:num('#leTurn',c.turn),opponentHP:num('#leOppHp'),pp:num('#lePp'),extraPP:val('#leExtra')||'unknown',ep:val('#leEp')||'unknown',sep:val('#leSep')||'unknown',opponentWard:val('#leWard')||'unknown',pirateFlagCountdowns:t.resources.pirateFlags.values,pirateFlagsKnown:t.resources.pirateFlags.known,knownBoardLeaderDamage:boardRaw===''?null:Math.max(0,Number(boardRaw)||0),boardDamageKnown:boardRaw!=='',otherConfirmedLeaderDamage:t.resources.otherConfirmedDamage.value,otherDamageKnown:t.resources.otherConfirmedDamage.known,tactical:t,hand:{barbaros:legacyStatus(t.cards.barbaros),zetaBeatrix:legacyStatus(t.cards.zetaBeatrix),quickBlader:legacyStatus(t.cards.quickBlader),cards:clone(t.cards),otherDamageRoutesChecked:t.resources.damageRoutesChecked},sideToAct:'自分',observedAtSeconds:Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null}}
function calculate(s=state()){const hp=Number.isFinite(Number(s.opponentHP))?Number(s.opponentHP):null,pp=Number.isFinite(Number(s.pp))?Number(s.pp):null,ex=s.extraPP??(s.extraPPAvailable==null?'unknown':s.extraPPAvailable?'yes':'no'),ep=s.ep??(s.epAvailable==null?'unknown':s.epAvailable?'yes':'no'),sep=s.sep??(s.sepAvailable==null?'unknown':s.sepAvailable?'yes':'no'),ward=typeof s.opponentWard==='string'?s.opponentWard:s.opponentWard===true?'present':s.opponentWard===false?'none':'unknown',tactical=normalizeTactical(s),bar=tactical.cards.barbaros,z=tactical.cards.zetaBeatrix,qb=tactical.cards.quickBlader,otherOk=!!tactical.resources.damageRoutesChecked,flagsKnown=!!tactical.resources.pirateFlags.known,boardKnown=s.boardDamageKnown!==false&&Number.isFinite(Number(s.knownBoardLeaderDamage)),otherKnown=!!tactical.resources.otherConfirmedDamage.known,eff=pp==null?null:pp+(bool(ex)===true?1:0),fixed=(boardKnown?Math.max(0,+s.knownBoardLeaderDamage||0):0)+(otherKnown?Math.max(0,+tactical.resources.otherConfirmedDamage.value||0):0),fs=flagsKnown?tactical.resources.pirateFlags.values.map(Number).filter(Number.isFinite):[],unknown=[],routes=[];
if(hp==null)unknown.push('相手HP');if(pp==null)unknown.push('PP');if(ex==='unknown')unknown.push('Extra PP');if(ep==='unknown')unknown.push('EP');if(sep==='unknown')unknown.push('SEP');if(ward==='unknown')unknown.push('守護');if(!boardKnown)unknown.push('場の攻撃可能総打点');if(!otherKnown)unknown.push('その他確定打点');for(const card of [bar,z,qb])if(!card.known)unknown.push(`${card.label}所持数`);if(bar.known&&bar.count>0&&!flagsKnown)unknown.push('海賊旗カウント');if(!otherOk)unknown.push('その他の即時打点候補');
const add=(name,cost,damage,category='other',meta={})=>routes.push({name,cost,damage,category,...meta,wardState:ward,lethal:hp!=null&&damage>=hp&&ward==='none'});
if(hp!=null&&boardKnown&&fixed>=hp)add('場＋その他確定打点',0,fixed,'board');
if(bar.known&&bar.count>0&&eff!=null&&eff>=7&&flagsKnown&&boardKnown){const d=4+fs.filter(x=>x<=5).length*2+fixed;add('バルバロス',7,d,'hand',{cardId:'barbaros'});if(bool(ep))add('バルバロス＋進化',7,d+2,'hand',{cardId:'barbaros'});if(bool(sep))add('バルバロス＋超進化',7,d+3,'hand',{cardId:'barbaros'})}
if(z.known&&z.count>0&&eff!=null&&eff>=6&&boardKnown){const d=3+fixed;add('ゼタ＆ベアトリクス（エンハンス6）',6,d,'hand',{cardId:'zetaBeatrix'});if(bool(ep))add('ゼタ＆ベアトリクス＋進化',6,d+2,'hand',{cardId:'zetaBeatrix'});if(bool(sep))add('ゼタ＆ベアトリクス＋超進化',6,d+3,'hand',{cardId:'zetaBeatrix'})}
if(qb.known&&qb.count>0&&eff!=null&&eff>=1&&boardKnown){const playable=Math.min(qb.count,Math.floor(eff)),base=playable+fixed;add(`刹那のクイックブレイダー×${playable}`,playable,base,'hand',{cardId:'quickBlader',copies:playable});if(bool(ep))add(`刹那のクイックブレイダー×${playable}＋進化`,playable,base+2,'hand',{cardId:'quickBlader',copies:playable});if(bool(sep))add(`刹那のクイックブレイダー×${playable}＋超進化`,playable,base+3,'hand',{cardId:'quickBlader',copies:playable})}
const lethalRoutes=routes.filter(x=>x.lethal).map(x=>x.name),status=lethalRoutes.length?'confirmed-lethal':unknown.length?'incomplete-do-not-declare-no-lethal':'checked-no-lethal-in-covered-routes';return{...clone(s),tactical,effectivePP:eff,routes,lethalRoutes,unknown,status}}
function tacticalSummary(x){const t=x.tactical||normalizeTactical(x),owned=TACTICAL_CARDS.map(def=>({def,state:t.cards[def.id]})).filter(x=>x.state?.known&&x.state.count>0).map(x=>`${x.def.label}×${x.state.count}`),unknownCards=TACTICAL_CARDS.filter(def=>!t.cards[def.id]?.known).map(def=>def.label),flags=t.resources.pirateFlags.known?(t.resources.pirateFlags.values.length?t.resources.pirateFlags.values.join(','):'0'):'未確認',other=t.resources.otherConfirmedDamage.known?`${t.resources.otherConfirmedDamage.value}点`:'未確認',handRoutes=(x.routes||[]).filter(r=>r.category==='hand').map(r=>`${r.name} ${r.damage}点`);return`戦術情報：${owned.length?owned.join(' / '):'所持確認なし'}
海賊旗：${flags}　その他確定打点：${other}　候補確認：${t.resources.damageRoutesChecked?'済':'未確認'}
即時打点候補：${handRoutes.length?handRoutes.join(' / '):'現在のPPでは計算可能候補なし'}${unknownCards.length?`\nカード未確認：${unknownCards.join(' / ')}`:''}`}
function renderLethal(){const o=W.$('#leResult');if(!o)return null;const x=calculate();window.__wbTacticalV1={catalog:clone(TACTICAL_CARDS),current:clone(x.tactical),routes:clone(x.routes.filter(r=>r.category==='hand'))};o.textContent=`${x.turn??'?'}T / 有効PP ${x.effectivePP??'?'} / 相手HP ${x.opponentHP??'?'}
${tacticalSummary(x)}

`+(x.routes.map(r=>`${r.lethal?'◎ ':''}${r.name}：${r.damage}点${r.wardState==='present'?'（守護あり）':r.wardState==='unknown'?'（守護未確認）':''}`).join('\n')||'該当する既知ルートはまだ計算できません。')+(x.lethalRoutes.length?`\nリーサル候補：${x.lethalRoutes.join(' / ')}`:x.unknown.length?`\n未確認：${x.unknown.join(' / ')}\n→「リーサルなし」と断定禁止`:'\n確認対象ルート内ではリーサルなし');return x}
function renderTacticalEditor(){const cb=W.$('#leTacticalCards'),rb=W.$('#leTacticalResources');if(cb)cb.innerHTML=TACTICAL_CARDS.map(card=>`<label class="tacticalItem"><span><b>${W.escape(card.label)}</b><small>${W.escape(card.category)}</small></span><select data-tactical-card="${card.id}"><option value="unknown">未確認</option><option value="0">なし</option>${Array.from({length:card.maxCount},(_,i)=>`<option value="${i+1}">${i+1}枚</option>`).join('')}</select></label>`).join('');if(rb)rb.innerHTML=TACTICAL_RESOURCES.map(r=>r.kind==='coverage'?`<label class="tacticalItem"><span><b>${W.escape(r.label)}</b><small>主要候補を確認したときだけ「確認済み」</small></span><select data-tactical-resource="${r.id}"><option value="unknown">未確認</option><option value="yes">確認済み</option></select></label>`:`<label class="tacticalItem"><span><b>${W.escape(r.label)}</b><small>${r.id==='pirateFlags'?'複数はカンマ区切り':'手札以外で確定している追加打点'}</small></span><input data-tactical-resource="${r.id}" type="${r.kind}" ${r.kind==='number'?'min="0"':''} placeholder="${W.escape(r.placeholder||'')}"></label>`).join('')}
function resetTacticalEditor(){for(const e of document.querySelectorAll('[data-tactical-card]'))e.value='unknown';for(const e of document.querySelectorAll('[data-tactical-resource]'))e.value=e.tagName==='SELECT'?'unknown':'';window.__wbTacticalV1={catalog:clone(TACTICAL_CARDS),current:readTactical(),routes:[]};renderLethal()}
function expose(){const l=ses(ld,false),c=ses(cd,false);window.__wbLethalV2={sourceKey:key(),snapshots:clone(l?.snapshots||[]),protocol:rules.protocol};window.__wbCounterfactualV1={sourceKey:key(),branches:clone(c?.branches||[]),protocol:{independentState:true}}}
function saveL(){const s=state(),critical=['extraPP','ep','sep','opponentWard'].filter(k=>s[k]==='unknown');if(critical.length){W.$('#leStatus').textContent=`保存しません：${critical.join(' / ')} が未確認です。`;return}const x=calculate(s),q=ses(ld);x.id='l'+Date.now().toString(36);x.createdAt=new Date().toISOString();q.snapshots.push(x);save(LS,ld);expose();W.$('#leStatus').textContent=`${x.turn??'?'}Tの状態を保存しました。`;renderSaved()}
function renderSaved(){const o=W.$('#leSaved'),q=ses(ld,false)?.snapshots||[];if(o)o.innerHTML=q.slice(-6).map(x=>`<div class="branchItem"><b>${x.turn??'?'}T</b><div>${x.lethalRoutes?.length?'候補：'+W.escape(x.lethalRoutes.join(' / ')):x.unknown?.length?'未確認：'+W.escape(x.unknown.join(' / ')):'主要候補内リーサルなし'}</div></div>`).join('')}
function cf(){return ses(cd)}
function branchEval(b){return b?.evaluation||b?.automation?.lethalResult||null}
function renderCf(){const o=W.$('#cfList'),q=cf()?.branches||[],p=W.$('#cfParent');if(p){const old=p.value;p.innerHTML='<option value="">親なし（起点）</option>'+q.map(b=>`<option value="${b.id}">${W.escape(b.name)} / ${b.state?.turn??'?'}T</option>`).join('');if(q.some(b=>b.id===old))p.value=old}if(o)o.innerHTML=q.map(b=>{const e=branchEval(b),txt=e?.lethalRoutes?.length?'リーサル候補 '+e.lethalRoutes.join(' / '):e?.status==='incomplete-do-not-declare-no-lethal'?'未確認あり':e?.status==='checked-no-lethal-in-covered-routes'?'主要既知ルート内リーサルなし':'';return`<div class="branchItem"><b>${W.escape(b.name)}</b><div>${b.state?.turn??'?'}T / 手番 ${W.escape(b.state?.sideToAct||'未設定')} / 判断時点 ${b.knowledgeCutoffSeconds??'?'}s${txt?`<br>${W.escape(txt)}`:''}</div></div>`}).join('');refreshAssist()}
function loadCurrentCf(){cfDraft={state:clone(state()),knowledgeCutoffSeconds:Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null};const st=W.$('#cfStatus');if(st)st.textContent=`現在のリーサル状態を分岐下書きへ取り込みました（${cfDraft.state.turn??'?'}T）。`;W.log('counterfactual-load-current',{turn:cfDraft.state.turn,cutoff:cfDraft.knowledgeCutoffSeconds})}
function newCf(){cfDraft=null;for(const id of ['#cfName','#cfNote']){const e=W.$(id);if(e)e.value=''}const p=W.$('#cfParent');if(p)p.value='';const side=W.$('#cfSide');if(side)side.value='自分';const kind=W.$('#cfKind');if(kind)kind.value='counterfactual';const st=W.$('#cfStatus');if(st)st.textContent='新しい分岐を入力できます。'}
function saveCf(){const q=cf(),name=String(val('#cfName')).trim();if(!q||!name){const st=W.$('#cfStatus');if(st)st.textContent='分岐名を入力してください。';return}const parentId=val('#cfParent')||null,parent=q.branches.find(b=>b.id===parentId);let s,cut;if(parent){s=clone(parent.state);cut=parent.knowledgeCutoffSeconds}else if(cfDraft){s=clone(cfDraft.state);cut=cfDraft.knowledgeCutoffSeconds}else{s=state();cut=Number.isFinite(W.video?.currentTime)?+W.video.currentTime.toFixed(2):null}if(cut==null)return;s.sideToAct=val('#cfSide')||'自分';const ev=calculate(s),b={id:'b'+Date.now().toString(36),name,kind:val('#cfKind')||'counterfactual',parentId,state:s,evaluation:{status:ev.status,lethalRoutes:ev.lethalRoutes,unknown:ev.unknown},knowledgeCutoffSeconds:cut,note:String(val('#cfNote')).trim(),origin:'clean-v4.11.0'};q.branches.push(b);save(CS,cd);cfDraft=null;expose();renderCf();W.$('#cfStatus').textContent=`「${name}」を独立状態として保存しました。`}
function sameTurnTemplate(src){const snaps=ses(ld,false)?.snapshots||[];return snaps.filter(x=>+x.turn===+src?.state?.turn&&Number.isFinite(+x.pp)).slice(-1)[0]||null}
function renderAssistTemplate(){const q=cf(),src=q?.branches.find(b=>b.id===val('#asSource')),o=W.$('#asTemplate');if(!o)return;if(!src){o.textContent='相手手番の起点を選択してください。';return}const tpl=sameTurnTemplate(src);o.textContent=tpl?`資源テンプレート：${src.state?.turn??'?'}T / PP ${tpl.pp} / ExPP ${tpl.extraPP??'unknown'} / EP ${tpl.ep??'unknown'} / SEP ${tpl.sep??'unknown'}`:'同ターンの保存済みリーサル状態がないため、PP/ExPP/EP/SEPは推測しません。'}
function renderAssistResults(){const o=W.$('#asResults'),q=cf()?.branches.filter(b=>b.origin==='branch-assist-clean')||[];if(!o)return;o.innerHTML=q.slice(-6).reverse().map(b=>{const r=b.automation?.lethalResult||{};const txt=r.lethalRoutes?.length?'候補：'+r.lethalRoutes.join(' / '):r.status==='incomplete-do-not-declare-no-lethal'?'未確認：'+(r.unknown||[]).join(' / '):'主要既知ルート内ではリーサルなし';return`<div class="branchItem"><b>${W.escape(b.name)}</b><div>${W.escape(txt)}</div></div>`}).join('')}
function refreshAssist(){const s=W.$('#asSource'),q=cf()?.branches.filter(b=>b.state?.sideToAct==='相手')||[];if(!s)return;const old=s.value;s.innerHTML=q.map(b=>`<option value="${b.id}">${W.escape(b.name)} / ${b.state?.turn??'?'}T</option>`).join('')||'<option value="">相手手番の起点がありません</option>';if(q.some(b=>b.id===old))s.value=old;renderAssistTemplate();renderAssistResults()}
function assist(){const q=cf(),src=q?.branches.find(b=>b.id===val('#asSource')),name=String(val('#asName')).trim();if(!src||!name){const st=W.$('#asStatus');if(st)st.textContent='相手手番の起点と返し名を指定してください。';return}const tpl=sameTurnTemplate(src),s=clone(src.state),fg=parseFlags(val('#asFlags')),boardRaw=String(val('#asBoard')).trim(),otherRaw=String(val('#asOther')).trim();s.sideToAct='自分';s.opponentHP=num('#asOppHp');s.selfHP=num('#asSelfHp');s.opponentWard=val('#asWard')||'unknown';s.pirateFlagCountdowns=fg.values;s.pirateFlagsKnown=fg.known;s.knownBoardLeaderDamage=boardRaw===''?null:Math.max(0,Number(boardRaw)||0);s.boardDamageKnown=boardRaw!=='';s.otherConfirmedLeaderDamage=otherRaw===''?null:Math.max(0,Number(otherRaw)||0);s.otherDamageKnown=otherRaw!=='';if(s.tactical?.resources){s.tactical.resources.pirateFlags={known:fg.known,values:fg.values.slice()};s.tactical.resources.otherConfirmedDamage={known:otherRaw!=='',value:otherRaw===''?null:Math.max(0,Number(otherRaw)||0)}}if(tpl){for(const k of ['pp','extraPP','ep','sep'])s[k]=tpl[k]??s[k]}else{s.pp=null;s.extraPP=s.ep=s.sep='unknown'}const r=calculate(s),b={id:'a'+Date.now().toString(36),name,kind:'counterfactual',parentId:src.id,state:s,knowledgeCutoffSeconds:src.knowledgeCutoffSeconds,note:String(val('#asNote')).trim(),origin:'branch-assist-clean',automation:{resourceStatus:tpl?'from-saved-lethal-snapshot':'missing-template',lethalResult:{status:r.status,lethalRoutes:r.lethalRoutes,unknown:r.unknown}}};q.branches.push(b);save(CS,cd);expose();renderCf();W.$('#asStatus').textContent=r.lethalRoutes.length?`「${name}」：リーサル候補 ${r.lethalRoutes.join(' / ')}`:r.status==='incomplete-do-not-declare-no-lethal'?`「${name}」：未確認情報あり。リーサルなしとは断定しません。`:`「${name}」：主要既知ルート内ではリーサルなし`}
W.ReviewEngine={version:V,rules,catalog:{cards:TACTICAL_CARDS,resources:TACTICAL_RESOURCES},calculate,state,normalizeTactical,readTactical,tacticalSummary,renderLethal,expose,renderTacticalEditor,resetTacticalEditor};
W.onReady(()=>{renderTacticalEditor();const tacticalChanged=e=>{if(e?.isTrusted)W.log('tactical-manual',{kind:e.target?.dataset?.tacticalCard?'card':'resource',id:e.target?.dataset?.tacticalCard||e.target?.dataset?.tacticalResource||null,value:e.target?.value??null,videoKey:W.videoKey()});renderLethal()};W.$('#leTacticalCards')?.addEventListener('change',tacticalChanged);W.$('#leTacticalResources')?.addEventListener('input',tacticalChanged);W.$('#leTacticalResources')?.addEventListener('change',tacticalChanged);W.$('#leCalc')?.addEventListener('click',renderLethal);W.$('#leSave')?.addEventListener('click',saveL);W.$('#cfLoadState')?.addEventListener('click',loadCurrentCf);W.$('#cfSave')?.addEventListener('click',saveCf);W.$('#cfNew')?.addEventListener('click',newCf);W.$('#asSource')?.addEventListener('change',renderAssistTemplate);W.$('#asCreate')?.addEventListener('click',assist);W.on('video-reset',()=>{cfDraft=null;resetTacticalEditor();expose();renderSaved();renderCf()});expose();renderLethal();renderSaved();renderCf();W.log('module-ready',{module:'review-engine',version:V,counterfactualUiComplete:true,branchAssistResults:true,tacticalCatalog:true,tacticalDynamicUi:true,quickBladerRoute:true})})})();
